# Setup

In [ ]:
pip install sleeper-api-wrapper

Collecting sleeper-api-wrapper
  Downloading sleeper_api_wrapper-1.1.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: requests<3.0.0,>=2.22.0 in /usr/local/lib/python3.10/dist-packages (from sleeper-api-wrapper) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.22.0->sleeper-api-wrapper) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.22.0->sleeper-api-wrapper) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.22.0->sleeper-api-wrapper) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.22.0->sleeper-api-wrapper) (2024.7.4)
Downloading sleeper_api_wrapper-1.1.0-py3-none-any.whl (10 kB)
Installing collected packages: sleeper-api-wrapper
Successfully installed sleeper-api-wrapper-1.1.0

In [ ]:
import sleeper_wrapper as sw

In [ ]:
league_2024 = sw.League(1120557302983110656)
league_2023 = sw.League(913920064179613696)
league_2022 = sw.League(856953821866364928)
league_2021 = sw.League(724847215113244672)
league_2020 = sw.League(515599187410649088)
league_2019 = sw.League(384599036419653632)
league_2018 = sw.League(332550784799502336)

In [ ]:
from sleeper_wrapper import Players
players = Players()
all_players = players.get_all_players(sport="nfl")

In [ ]:
import pandas as pd
players_df = pd.DataFrame.from_dict(all_players, orient='index')

In [ ]:
players_df = players_df.dropna(axis=1, how='all').dropna(axis=1, thresh=2)

In [ ]:
players_df.to_parquet(path='/content/drive/MyDrive/ff/sleeper_players.parquet', compression='snappy')

In [ ]:
pip install nfl_data_py

Collecting nfl_data_py
  Downloading nfl_data_py-0.3.2-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: pandas>1 in /usr/local/lib/python3.10/dist-packages (from nfl_data_py) (2.1.4)
Collecting appdirs>1 (from nfl_data_py)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting fastparquet>0.5 (from nfl_data_py)
  Downloading fastparquet-2024.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from fastparquet>0.5->nfl_data_py) (1.26.4)
Collecting cramjam>=2.3 (from fastparquet>0.5->nfl_data_py)
  Downloading cramjam-2.8.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from fastparquet>0.5->nfl_data_py) (2024.6.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from fastparquet>0.5->nfl_data_py) (24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>1->nfl_data_py) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>1->nfl_data_py) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>1->nfl_data_py) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>1->nfl_data_py) (1.16.0)
Downloading nfl_data_py-0.3.2-py3-none-any.whl (13 kB)
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading fastparquet-2024.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 33.0 MB/s eta 0:00:00
Downloading cramjam-2.8.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 52.8 MB/s eta 0:00:00
Installing collected packages: appdirs, cramjam, fastparquet, nfl_data_py
Successfully installed appdirs-1.4.4 cramjam-2.8.3 fastparquet-2024.5.0 nfl_data_py-0.3.2

In [ ]:
import nfl_data_py as nfl

In [ ]:
nfl_weekly = nfl.import_weekly_data([2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014], downcast=True)

Downcasting floats.

In [ ]:
nfl_pbp = nfl.import_pbp_data([2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014], downcast=True)

2023 done.
2022 done.
2021 done.
2020 done.
2019 done.
2018 done.
2017 done.
2016 done.
2015 done.
2014 done.
Downcasting floats.

In [ ]:
dict(nfl_pbp.iloc[4])

{'play_id': 102.0,
 'game_id': '2023_01_ARI_WAS',
 'old_game_id': '2023091007',
 'home_team': 'WAS',
 'away_team': 'ARI',
 'season_type': 'REG',
 'week': 1,
 'posteam': 'WAS',
 'posteam_type': 'home',
 'defteam': 'ARI',
 'side_of_field': 'WAS',
 'yardline_100': 66.0,
 'game_date': '2023-09-10',
 'quarter_seconds_remaining': 835.0,
 'half_seconds_remaining': 1735.0,
 'game_seconds_remaining': 3535.0,
 'game_half': 'Half1',
 'quarter_end': 0.0,
 'drive': 1.0,
 'sp': 0.0,
 'qtr': 1.0,
 'down': 3.0,
 'goal_to_go': 0,
 'time': '13:55',
 'yrdln': 'WAS 34',
 'ydstogo': 1.0,
 'ydsnet': 26.0,
 'desc': '(13:55) 23-C.Rodriguez left guard to WAS 36 for 2 yards (97-C.Thomas; 25-Z.Collins).',
 'play_type': 'run',
 'yards_gained': 2.0,
 'shotgun': 0.0,
 'no_huddle': 0.0,
 'qb_dropback': 0.0,
 'qb_kneel': 0.0,
 'qb_spike': 0.0,
 'qb_scramble': 0.0,
 'pass_length': None,
 'pass_location': None,
 'air_yards': nan,
 'yards_after_catch': nan,
 'run_location': 'left',
 'run_gap': 'guard',
 'field_goal_result': None,
 'kick_distance': nan,
 'extra_point_result': None,
 'two_point_conv_result': None,
 'home_timeouts_remaining': 3.0,
 'away_timeouts_remaining': 3.0,
 'timeout': 0.0,
 'timeout_team': None,
 'td_team': None,
 'td_player_name': None,
 'td_player_id': None,
 'posteam_timeouts_remaining': 3.0,
 'defteam_timeouts_remaining': 3.0,
 'total_home_score': 0.0,
 'total_away_score': 0.0,
 'posteam_score': 0.0,
 'defteam_score': 0.0,
 'score_differential': 0.0,
 'posteam_score_post': 0.0,
 'defteam_score_post': 0.0,
 'score_differential_post': 0.0,
 'no_score_prob': 0.005151121,
 'opp_fg_prob': 0.14255205,
 'opp_safety_prob': 0.002266304,
 'opp_td_prob': 0.20016445,
 'fg_prob': 0.21326233,
 'safety_prob': 0.0042742593,
 'td_prob': 0.43232948,
 'extra_point_prob': 0.0,
 'two_point_conversion_prob': 0.0,
 'ep': 1.8413019,
 'epa': 0.46979922,
 'total_home_epa': 0.8370034,
 'total_away_epa': -0.8370034,
 'total_home_rush_epa': 0.13369575,
 'total_away_rush_epa': -0.13369575,
 'total_home_pass_epa': 0.7033076,
 'total_away_pass_epa': -0.7033076,
 'air_epa': nan,
 'yac_epa': nan,
 'comp_air_epa': 0.0,
 'comp_yac_epa': 0.0,
 'total_home_comp_air_epa': 0.7033076,
 'total_away_comp_air_epa': -0.7033076,
 'total_home_comp_yac_epa': 0.0,
 'total_away_comp_yac_epa': 0.0,
 'total_home_raw_air_epa': 0.7033076,
 'total_away_raw_air_epa': -0.7033076,
 'total_home_raw_yac_epa': 0.0,
 'total_away_raw_yac_epa': 0.0,
 'wp': 0.5559875,
 'def_wp': 0.44401252,
 'home_wp': 0.5559875,
 'away_wp': 0.44401252,
 'wpa': 0.016585886,
 'vegas_wpa': 0.012498915,
 'vegas_home_wpa': 0.012498915,
 'home_wp_post': 0.57257336,
 'away_wp_post': 0.42742664,
 'vegas_wp': 0.7281498,
 'vegas_home_wp': 0.7281498,
 'total_home_rush_wpa': 0.009945035,
 'total_away_rush_wpa': -0.009945035,
 'total_home_pass_wpa': 0.016366541,
 'total_away_pass_wpa': -0.016366541,
 'air_wpa': nan,
 'yac_wpa': nan,
 'comp_air_wpa': 0.0,
 'comp_yac_wpa': 0.0,
 'total_home_comp_air_wpa': 0.016366541,
 'total_away_comp_air_wpa': -0.016366541,
 'total_home_comp_yac_wpa': 0.0,
 'total_away_comp_yac_wpa': 0.0,
 'total_home_raw_air_wpa': 0.016366541,
 'total_away_raw_air_wpa': -0.016366541,
 'total_home_raw_yac_wpa': 0.0,
 'total_away_raw_yac_wpa': 0.0,
 'punt_blocked': 0.0,
 'first_down_rush': 1.0,
 'first_down_pass': 0.0,
 'first_down_penalty': 0.0,
 'third_down_converted': 1.0,
 'third_down_failed': 0.0,
 'fourth_down_converted': 0.0,
 'fourth_down_failed': 0.0,
 'incomplete_pass': 0.0,
 'touchback': 0.0,
 'interception': 0.0,
 'punt_inside_twenty': 0.0,
 'punt_in_endzone': 0.0,
 'punt_out_of_bounds': 0.0,
 'punt_downed': 0.0,
 'punt_fair_catch': 0.0,
 'kickoff_inside_twenty': 0.0,
 'kickoff_in_endzone': 0.0,
 'kickoff_out_of_bounds': 0.0,
 'kickoff_downed': 0.0,
 'kickoff_fair_catch': 0.0,
 'fumble_forced': 0.0,
 'fumble_not_forced': 0.0,
 'fumble_out_of_bounds': 0.0,
 'solo_tackle': 0.0,
 'safety': 0.0,
 'penalty': 0.0,
 'tackled_for_loss': 0.0,
 'fumble_lost': 0.0,
 'own_kickoff_recovery': 0.0,
 'own_kickoff_recovery_td': 0.0,
 'qb_hit': 0.0,
 'rush_attempt': 1.0,
 'pass_attempt': 0.0,
 'sack': 0.0,
 'touchdown': 0.0,
 'pass_touchdown': 0.0,
 'rush_touchdown': 0.0,
 'return_touchdown': 0.0,
 'extra_point_attempt': 0.0,
 'two_point_attempt': 0.0,
 'field_goal_attempt': 0.0,
 'kickoff_attempt': 0.0,
 'punt_attempt': 0.0,
 'fumble': 0.0,
 'complete_pass': 0.0,
 'assist_tackle': 1.0,
 'lateral_reception': 0.0,
 'lateral_rush': 0.0,
 'lateral_return': 0.0,
 'lateral_recovery': 0.0,
 'passer_player_id': None,
 'passer_player_name': None,
 'passing_yards': nan,
 'receiver_player_id': None,
 'receiver_player_name': None,
 'receiving_yards': nan,
 'rusher_player_id': '00-0038611',
 'rusher_player_name': 'C.Rodriguez',
 'rushing_yards': 2.0,
 'lateral_receiver_player_id': None,
 'lateral_receiver_player_name': None,
 'lateral_receiving_yards': nan,
 'lateral_rusher_player_id': None,
 'lateral_rusher_player_name': None,
 'lateral_rushing_yards': nan,
 'lateral_sack_player_id': None,
 'lateral_sack_player_name': None,
 'interception_player_id': None,
 'interception_player_name': None,
 'lateral_interception_player_id': None,
 'lateral_interception_player_name': None,
 'punt_returner_player_id': None,
 'punt_returner_player_name': None,
 'lateral_punt_returner_player_id': None,
 'lateral_punt_returner_player_name': None,
 'kickoff_returner_player_name': None,
 'kickoff_returner_player_id': None,
 'lateral_kickoff_returner_player_id': None,
 'lateral_kickoff_returner_player_name': None,
 'punter_player_id': None,
 'punter_player_name': None,
 'kicker_player_name': None,
 'kicker_player_id': None,
 'own_kickoff_recovery_player_id': None,
 'own_kickoff_recovery_player_name': None,
 'blocked_player_id': None,
 'blocked_player_name': None,
 'tackle_for_loss_1_player_id': None,
 'tackle_for_loss_1_player_name': None,
 'tackle_for_loss_2_player_id': None,
 'tackle_for_loss_2_player_name': None,
 'qb_hit_1_player_id': None,
 'qb_hit_1_player_name': None,
 'qb_hit_2_player_id': None,
 'qb_hit_2_player_name': None,
 'forced_fumble_player_1_team': None,
 'forced_fumble_player_1_player_id': None,
 'forced_fumble_player_1_player_name': None,
 'forced_fumble_player_2_team': None,
 'forced_fumble_player_2_player_id': None,
 'forced_fumble_player_2_player_name': None,
 'solo_tackle_1_team': None,
 'solo_tackle_2_team': None,
 'solo_tackle_1_player_id': None,
 'solo_tackle_2_player_id': None,
 'solo_tackle_1_player_name': None,
 'solo_tackle_2_player_name': None,
 'assist_tackle_1_player_id': '00-0037815',
 'assist_tackle_1_player_name': 'C.Thomas',
 'assist_tackle_1_team': 'ARI',
 'assist_tackle_2_player_id': '00-0036933',
 'assist_tackle_2_player_name': 'Z.Collins',
 'assist_tackle_2_team': 'ARI',
 'assist_tackle_3_player_id': None,
 'assist_tackle_3_player_name': None,
 'assist_tackle_3_team': None,
 'assist_tackle_4_player_id': None,
 'assist_tackle_4_player_name': None,
 'assist_tackle_4_team': None,
 'tackle_with_assist': 0.0,
 'tackle_with_assist_1_player_id': None,
 'tackle_with_assist_1_player_name': None,
 'tackle_with_assist_1_team': None,
 'tackle_with_assist_2_player_id': None,
 'tackle_with_assist_2_player_name': None,
 'tackle_with_assist_2_team': None,
 'pass_defense_1_player_id': None,
 'pass_defense_1_player_name': None,
 'pass_defense_2_player_id': None,
 'pass_defense_2_player_name': None,
 'fumbled_1_team': None,
 'fumbled_1_player_id': None,
 'fumbled_1_player_name': None,
 'fumbled_2_player_id': None,
 'fumbled_2_player_name': None,
 'fumbled_2_team': None,
 'fumble_recovery_1_team': None,
 'fumble_recovery_1_yards': nan,
 'fumble_recovery_1_player_id': None,
 'fumble_recovery_1_player_name': None,
 'fumble_recovery_2_team': None,
 'fumble_recovery_2_yards': nan,
 'fumble_recovery_2_player_id': None,
 'fumble_recovery_2_player_name': None,
 'sack_player_id': None,
 'sack_player_name': None,
 'half_sack_1_player_id': None,
 'half_sack_1_player_name': None,
 'half_sack_2_player_id': None,
 'half_sack_2_player_name': None,
 'return_team': None,
 'return_yards': 0.0,
 'penalty_team': None,
 'penalty_player_id': None,
 'penalty_player_name': None,
 'penalty_yards': nan,
 'replay_or_challenge': 0.0,
 'replay_or_challenge_result': None,
 'penalty_type': None,
 'defensive_two_point_attempt': 0.0,
 'defensive_two_point_conv': 0.0,
 'defensive_extra_point_attempt': 0.0,
 'defensive_extra_point_conv': 0.0,
 'safety_player_name': None,
 'safety_player_id': None,
 'season': 2023,
 'cp': nan,
 'cpoe': nan,
 'series': 1.0,
 'series_success': 1.0,
 'series_result': 'First down',
 'order_sequence': 102.0,
 'start_time': '9/10/23, 13:02:43',
 'time_of_day': '2023-09-10T17:04:27.237Z',
 'stadium': 'Commanders Field',
 'weather': 'Cloudy Temp: 76° F, Humidity: 84%, Wind: S 2 mph',
 'nfl_api_id': 'b07c705e-f053-11ed-b4a7-bab79e4492fa',
 'play_clock': '0',
 'play_deleted': 0.0,
 'play_type_nfl': 'RUSH',
 'special_teams_play': 0.0,
 'st_play_type': None,
 'end_clock_time': '2023-09-10T17:04:31.717Z',
 'end_yard_line': None,
 'fixed_drive': 1.0,
 'fixed_drive_result': 'Punt',
 'drive_real_start_time': '2023-09-10T17:02:43.600Z',
 'drive_play_count': 8.0,
 'drive_time_of_possession': '4:01',
 'drive_first_downs': 2.0,
 'drive_inside20': 0.0,
 'drive_ended_with_score': 0.0,
 'drive_quarter_start': 1.0,
 'drive_quarter_end': 1.0,
 'drive_yards_penalized': 0.0,
 'drive_start_transition': 'KICKOFF',
 'drive_end_transition': 'PUNT',
 'drive_game_clock_start': '15:00',
 'drive_game_clock_end': '10:59',
 'drive_start_yard_line': 'WAS 25',
 'drive_end_yard_line': 'ARI 49',
 'drive_play_id_started': 39.0,
 'drive_play_id_ended': 245.0,
 'away_score': 16,
 'home_score': 20,
 'location': 'Home',
 'result': 4,
 'total': 36,
 'spread_line': 7.0,
 'total_line': 38.0,
 'div_game': 0,
 'roof': 'outdoors',
 'surface': '',
 'temp': nan,
 'wind': nan,
 'home_coach': 'Ron Rivera',
 'away_coach': 'Jonathan Gannon',
 'stadium_id': 'WAS00',
 'game_stadium': 'FedExField',
 'aborted_play': 0.0,
 'success': 1.0,
 'passer': None,
 'passer_jersey_number': nan,
 'rusher': 'C.Rodriguez',
 'rusher_jersey_number': 23.0,
 'receiver': None,
 'receiver_jersey_number': nan,
 'pass': 0.0,
 'rush': 1.0,
 'first_down': 1.0,
 'special': 0.0,
 'play': 1.0,
 'passer_id': None,
 'rusher_id': '00-0038611',
 'receiver_id': None,
 'name': 'C.Rodriguez',
 'jersey_number': 23.0,
 'id': '00-0038611',
 'fantasy_player_name': 'C.Rodriguez',
 'fantasy_player_id': '00-0038611',
 'fantasy': 'C.Rodriguez',
 'fantasy_id': '00-0038611',
 'out_of_bounds': 0.0,
 'home_opening_kickoff': 1.0,
 'qb_epa': 0.46979922,
 'xyac_epa': nan,
 'xyac_mean_yardage': nan,
 'xyac_median_yardage': nan,
 'xyac_success': nan,
 'xyac_fd': nan,
 'xpass': 0.19606467,
 'pass_oe': -19.606466,
 'nflverse_game_id': '2023_01_ARI_WAS',
 'possession_team': 'WAS',
 'offense_formation': 'I_FORM',
 'offense_personnel': '1 RB, 1 TE, 3 WR',
 'defenders_in_box': 6.0,
 'defense_personnel': '2 DL, 4 LB, 5 DB',
 'number_of_pass_rushers': nan,
 'players_on_play': '49410;41475;47812;52516;46629;53445;41349;53480;46188;56045;44848;54609;54481;47859;44852;52535;46968;54552;48473;56058;53565;45695',
 'offense_players': '00-0031095;00-0036334;00-0034445;00-0031260;00-0036618;00-0037077;00-0037741;00-0035659;00-0033282;00-0038611;00-0033831',
 'defense_players': '00-0035705;00-0035636;00-0036933;00-0034375;00-0038984;00-0033890;00-0036395;00-0034801;00-0037815;00-0035343;00-0036884',
 'n_offense': 11.0,
 'n_defense': 11.0,
 'ngs_air_yards': nan,
 'time_to_throw': nan,
 'was_pressure': None,
 'route': None,
 'defense_man_zone_type': None,
 'defense_coverage_type': None}

In [ ]:
pids_df = nfl.import_ids()
pids_df.to_parquet(path='/content/drive/MyDrive/ff/nfl_data/pids_df.parquet', compression='snappy')

In [ ]:
pids_df['sleeper_id'] = pids_df['sleeper_id'].fillna(-1).astype('int32')
pids_df[['sleeper_id','gsis_id','pfr_id','name']]

       sleeper_id gsis_id pfr_id               name
0           11560     NaN    NaN     Caleb Williams
1           11564     NaN    NaN         Drake Maye
2           11566     NaN    NaN     Jayden Daniels
3           11563     NaN    NaN             Bo Nix
4           11559     NaN    NaN  Michael Penix Jr.
...           ...     ...    ...                ...
11691          -1     NaN    NaN         Doug Brien
11692          -1     NaN    NaN     Jeremy Brigham
11693          -1     NaN    NaN     Vincent Brisby
11694          -1     NaN    NaN      Bubby Brister
11695          -1     NaN    NaN    Lorenzo Bromell

[11696 rows x 4 columns]

In [ ]:
years = [2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014]

In [ ]:
nfl_seasonal = nfl.import_seasonal_data(years, 'ALL')

In [ ]:
nfl_seasonal.to_parquet(path='/content/drive/MyDrive/ff/nfl_data/nfl_seasonal.parquet', compression='snappy')

In [ ]:
nfl_seasonal

,player_id,season,season_type,completions,attempts,passing_yards,passing_tds,interceptions,sacks,sack_yards,...,yac_sh,wopr_y,ry_sh,rtd_sh,rfd_sh,rtdfd_sh,dom,w8dom,yptmpa,ppr_sh
0,00-0007091,2014,REG,30,44,301.0,2,0.0,2.0,7.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.037559
1,00-0007091,2015,REG,156,256,1690.0,9,5.0,16.0,101.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.159657
2,00-0010346,2014,POST,26,46,211.0,1,0.0,2.0,11.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.181640
3,00-0010346,2014,REG,395,597,4727.0,39,15.0,17.0,118.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.181640
4,00-0010346,2015,POST,51,92,539.0,2,1.0,9.0,75.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.120107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7446,00-0039152,2023,REG,149,255,1808.0,8,4.0,28.0,185.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.159821
7447,00-0039163,2023,POST,35,54,449.0,3,0.0,0.0,0.0,...,0.000491,0.002508,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.206308
7448,00-0039163,2023,REG,319,499,4108.0,23,5.0,38.0,331.0,...,0.000491,0.002508,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.206308
7449,00-0039164,2023,REG,50,84,577.0,3,1.0,7.0,29.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.213689
7450,00-0039165,2023,REG,0,0,0.0,0,0.0,0.0,0.0,...,0.125506,0.100465,0.052938,0.0,0.039326,0.035176,0.026469,0.042351,0.37931,0.080979

Warning: Total number of columns (58) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
nfl_seasonal_rosters = nfl.import_seasonal_rosters(years)

In [ ]:
nfl_seasonal_rosters.to_csv('/content/drive/MyDrive/ff/nfl_data/nfl_seasonal_rosters.csv')

In [ ]:
nfl_weekly_rosters_2023 = nfl.import_weekly_rosters([2023])
nfl_weekly_rosters_2022 = nfl.import_weekly_rosters([2022])
nfl_weekly_rosters_2021 = nfl.import_weekly_rosters([2021])
nfl_weekly_rosters_2020 = nfl.import_weekly_rosters([2020])
nfl_weekly_rosters_2019 = nfl.import_weekly_rosters([2019])
nfl_weekly_rosters_2018 = nfl.import_weekly_rosters([2018])
nfl_weekly_rosters_2017 = nfl.import_weekly_rosters([2017])
nfl_weekly_rosters_2016 = nfl.import_weekly_rosters([2016])
nfl_weekly_rosters_2015 = nfl.import_weekly_rosters([2015])
nfl_weekly_rosters_2014 = nfl.import_weekly_rosters([2014])

In [ ]:
nfl_weekly_rosters = pd.concat([nfl_weekly_rosters_2023, nfl_weekly_rosters_2022, nfl_weekly_rosters_2021, nfl_weekly_rosters_2020,nfl_weekly_rosters_2019,nfl_weekly_rosters_2018,nfl_weekly_rosters_2017,nfl_weekly_rosters_2016,nfl_weekly_rosters_2015,nfl_weekly_rosters_2014], ignore_index=True)
nfl_weekly_rosters.to_csv('/content/drive/MyDrive/ff/nfl_data/nfl_weekly_rosters.csv')

In [ ]:
#rosters have some mixed types that parquet doesn't like.

In [ ]:
nfl_weekly_rosters_2023.iloc[200]['headshot_url']

'https://static.www.nfl.com/image/private/f_auto,q_auto/league/icjfdfsncqlsqe49iujv'

In [ ]:
nfl_officials = nfl.import_officials(years)

In [ ]:
nfl_officials.to_parquet(path='/content/drive/MyDrive/ff/nfl_data/nfl_officials.parquet', compression='snappy')

In [ ]:
nfl_draft_picks = nfl.import_draft_picks(years)

In [ ]:
nfl_draft_picks.to_parquet(path='/content/drive/MyDrive/ff/nfl_data/nfl_draft_picks.parquet', compression='snappy')

In [ ]:
nfl_draft_values = nfl.import_draft_values()

In [ ]:
nfl_draft_values.to_parquet(path='/content/drive/MyDrive/ff/nfl_data/nfl_draft_values.parquet', compression='snappy')

In [ ]:
nfl_team_desc = nfl.import_team_desc()

In [ ]:
nfl_team_desc.to_parquet(path='/content/drive/MyDrive/ff/nfl_data/nfl_team_desc.parquet', compression='snappy')

In [ ]:
nfl_schedules = nfl.import_schedules(years)

In [ ]:
nfl_schedules.to_parquet(path='/content/drive/MyDrive/ff/nfl_data/nfl_schedules.parquet', compression='snappy')

In [ ]:
nfl_combine = nfl.import_combine_data(years)

In [ ]:
nfl_combine.to_parquet(path='/content/drive/MyDrive/ff/nfl_data/nfl_combine.parquet', compression='snappy')

In [ ]:
nfl_ngs_passing = nfl.import_ngs_data('passing', years)
nfl_ngs_rushing = nfl.import_ngs_data('rushing', years)
nfl_ngs_receiving = nfl.import_ngs_data('receiving', years)

In [ ]:
nfl_ngs_passing.to_parquet(path='/content/drive/MyDrive/ff/nfl_data/nfl_ngs_passing.parquet', compression='snappy')
nfl_ngs_rushing.to_parquet(path='/content/drive/MyDrive/ff/nfl_data/nfl_ngs_rushing.parquet', compression='snappy')
nfl_ngs_receiving.to_parquet(path='/content/drive/MyDrive/ff/nfl_data/nfl_ngs_receiving.parquet', compression='snappy')

In [ ]:
nfl_ngs_rushing

,season,season_type,week,player_display_name,player_position,team_abbr,efficiency,percent_attempts_gte_eight_defenders,avg_time_to_los,rush_attempts,...,rush_yards_over_expected,avg_rush_yards,rush_yards_over_expected_per_att,rush_pct_over_expected,rush_touchdowns,player_gsis_id,player_first_name,player_last_name,player_jersey_number,player_short_name
0,2016,REG,0,Latavius Murray,RB,LV,3.913071,45.641026,2.589171,195,...,-0.997213,4.041026,-0.997213,0.000000,12,00-0030513,Latavius,Murray,28,L.Murray
1,2016,REG,0,Tim Hightower,RB,NO,3.737044,27.819549,2.553855,133,...,NaN,4.120301,NaN,NaN,4,00-0026289,Tim,Hightower,34,T.Hightower
2,2016,REG,0,Matt Asiata,RB,MIN,3.999453,38.842975,2.256416,121,...,NaN,3.322314,NaN,NaN,6,00-0028198,Matt,Asiata,44,M.Asiata
3,2016,REG,0,David Johnson,RB,ARI,3.869201,25.597270,2.637508,293,...,NaN,4.228669,NaN,NaN,16,00-0032187,David,Johnson,31,D.Johnson
4,2016,REG,0,Jonathan Stewart,RB,CAR,4.379927,38.073394,2.834390,218,...,NaN,3.779817,NaN,NaN,9,00-0026153,Jonathan,Stewart,28,J.Stewart
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4805,2023,POST,21,Isiah Pacheco,RB,KC,4.510882,37.500000,2.815727,24,...,-23.925928,2.833333,-1.087542,0.318182,1,00-0037197,Isiah,Pacheco,10,I.Pacheco
4806,2023,POST,21,Christian McCaffrey,RB,SF,4.052778,50.000000,2.762667,20,...,16.028502,4.500000,0.801425,0.450000,2,00-0033280,Christian,McCaffrey,23,C.McCaffrey
4807,2023,POST,21,Jahmyr Gibbs,RB,DET,5.399333,16.666667,3.223778,12,...,-13.030386,3.750000,-1.085866,0.333333,1,00-0039139,Jahmyr,Gibbs,26,J.Gibbs
4808,2023,POST,23,Christian McCaffrey,RB,SF,4.606375,22.727273,2.767900,22,...,-11.664819,3.636364,-0.530219,0.318182,0,00-0033280,Christian,McCaffrey,23,C.McCaffrey
4809,2023,POST,23,Isiah Pacheco,RB,KC,3.927797,0.000000,2.813471,18,...,-16.930108,3.277778,-0.940562,0.277778,0,00-0037197,Isiah,Pacheco,10,I.Pacheco

In [ ]:
nfl_qbr_weekly = nfl.import_qbr(years, 'nfl', 'weekly')
nfl_qbr_seasonal = nfl.import_qbr(years, 'nfl', 'season')

In [ ]:
nfl_qbr_weekly.to_parquet(path='/content/drive/MyDrive/ff/nfl_data/nfl_qbr_weekly.parquet', compression='snappy')
nfl_qbr_seasonal.to_parquet(path='/content/drive/MyDrive/ff/nfl_data/nfl_qbr_seasonal.parquet', compression='snappy')

In [ ]:
nfl_pfr_seasonal_pass = nfl.import_seasonal_pfr('pass', [2023, 2022, 2021, 2020, 2019, 2018])
nfl_pfr_seasonal_rec = nfl.import_seasonal_pfr('rec', [2023, 2022, 2021, 2020, 2019, 2018])
nfl_pfr_seasonal_rush = nfl.import_seasonal_pfr('rush', [2023, 2022, 2021, 2020, 2019, 2018])
nfl_pfr_weekly_pass = nfl.import_weekly_pfr('pass', [2023, 2022, 2021, 2020, 2019, 2018])
nfl_pfr_weekly_rec = nfl.import_weekly_pfr('rec', [2023, 2022, 2021, 2020, 2019, 2018])
nfl_pfr_weekly_rush = nfl.import_weekly_pfr('rush', [2023, 2022, 2021, 2020, 2019, 2018])

In [ ]:
nfl_pfr_seasonal_pass.to_parquet(path='/content/drive/MyDrive/ff/nfl_data/nfl_pfr_seasonal_pass.parquet', compression='snappy')
nfl_pfr_seasonal_rec.to_parquet(path='/content/drive/MyDrive/ff/nfl_data/nfl_pfr_seasonal_rec.parquet', compression='snappy')
nfl_pfr_seasonal_rush.to_parquet(path='/content/drive/MyDrive/ff/nfl_data/nfl_pfr_seasonal_rush.parquet', compression='snappy')
nfl_pfr_weekly_pass.to_parquet(path='/content/drive/MyDrive/ff/nfl_data/nfl_pfr_weekly_pass.parquet', compression='snappy')
nfl_pfr_weekly_rec.to_parquet(path='/content/drive/MyDrive/ff/nfl_data/nfl_pfr_weekly_rec.parquet', compression='snappy')
nfl_pfr_weekly_rush.to_parquet(path='/content/drive/MyDrive/ff/nfl_data/nfl_pfr_weekly_rush.parquet', compression='snappy')

In [ ]:
nfl_pfr_seasonal_pass.iloc[550]

player             Trevor Lawrence
team                           JAX
pass_attempts                564.0
throwaways                    12.0
spikes                         0.0
drops                         24.0
drop_pct                       4.3
bad_throws                   104.0
bad_throw_pct                 18.8
season                        2023
pfr_id                    LawrTr00
pocket_time                    2.2
times_blitzed                158.0
times_hurried                 39.0
times_hit                     42.0
times_pressured              116.0
pressure_pct                  18.1
batted_balls                  16.0
on_tgt_throws                410.0
on_tgt_pct                    74.3
rpo_plays                     77.0
rpo_yards                    510.0
rpo_pass_att                  65.0
rpo_pass_yards               449.0
rpo_rush_att                  10.0
rpo_rush_yards                61.0
pa_pass_att                   85.0
pa_pass_yards                875.0
Name: 550, dtype: object

In [ ]:
nfl_snap_count = nfl.import_snap_counts(years)

In [ ]:
nfl_snap_count.to_parquet(path='/content/drive/MyDrive/ff/nfl_data/nfl_snap_count.parquet', compression='snappy')

In [ ]:
nfl_ftn_data = nfl.import_ftn_data([2023, 2022], downcast=True)

Downcasting floats.

In [ ]:
nfl_ftn_data.to_parquet(path='/content/drive/MyDrive/ff/nfl_data/nfl_ftn_data.parquet', compression='snappy')

In [ ]:
nfl.cache_pbp(years, downcast=True, alt_path='/content/drive/My Drive/ff/nfl_cache')

2023 done.
2022 done.
2021 done.
2020 done.
2019 done.
2018 done.
2017 done.
2016 done.
2015 done.
2014 done.

In [ ]:
#going forward, pull pbp data like so:
#years = [2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014]
#nfl_pbp = nfl.import_pbp_data(years, downcast=True, cache=True, alt_path='/content/drive/My Drive/ff/nfl_cache')

| field	| data_type	| description | API access |
| ----- | --------- | ----------- | -----------|
|mfl_id	|character	|MyFantasyLeague.com ID - this is the primary key for this table and is unique and complete. Usually an integer of 5 digits.| available, not really useful |
|sportradar_id|	character	|SportRadar ID - often also called sportsdata_id by other services. A UUID.| $$$ |
|fantasypros_id|	character	|FantasyPros.com ID - usually an integer of 5 digits.| ? |
|gsis_id|	character|	NFL Game Stats and Information Services - usually starts with 00- and is followed by a series of integers.| used by most (all?) of the nfl-data tables |
|pff_id	|character	|Pro Football Focus ID - usually an integer with between 3 and 6 digits.| $ |
|sleeper_id|	character|	Sleeper ID - usually an integer with ~4 digits.|
|nfl_id	|character|	NFL.com ID - usual format fullname/integers| pip install sleeper-api-wrapper |
|espn_id	|character|	ESPN ID - usual format is an integer with ~5 digits| very good https://gist.github.com/nntrn/ee26cb2a0716de0947a0a4e9a157bc1c |
|yahoo_id	|character	|Yahoo ID - usual format is an integer with ~5 digits| no point |
|fleaflicker_id	|character	|Fleaflicker ID - usual format is an integer with ~4 digits. Fleaflicker API also has sportradar and that’s generally preferred.||
|cbs_id	|character|	CBS ID - usual format is an integer with ~ 7 digits.||
|rotowire_id|	character	|Rotowire ID - usual format is an integer with ~four digits. Not to be confused with rotowire_id.||
|rotoworld_id	|character	|Rotoworld ID - usual format is an integer with ~four digits. Not to be confused with rotowire_id.||
|ktc_id	|character	|KeepTradeCut ID - usual format is an integer with ~four digits.||
|pfr_id	|character	|Pro Football Reference ID - usual format is first four characters of last name, first two characters of first name, and an integer| no, scraping though |
|cfbref_id	|character	|College Football Reference ID - usual format is firstname-lastname-integer| |
|stats_id|	character|	Stats ID - usual format is five digit integer| |
|stats_global_id	|character	|Stats Global ID - usual format is a six digit integer| |
|fantasy_data_id|	character	|FantasyData ID - usual format five digit integer| $ |
|name|	character|	Name, as reported by MFL but reordered into FirstName LastName instead of Last, First| |
|merge_name	|character	|Name but formatted for name joins via ffscrapr::dp_cleannames() - coerced to lowercase, stripped of punctuation and suffixes, and common substitutions performed.| |
|position	|character|Position as reported by MFL| |
|team	|character	|Team as reported by MFL| |
|birthdate|	date|	Birthdate| |
|age|	numeric	|Age as of last pipeline build, rounded to one decimal. Pipeline is built on a weekly basis. | |
|draft_year	|numeric	|Year of draft. Zero if unknown/undrafted.| |
|draft_round	|numeric|	Round of draft.| |
|draft_pick	|numeric	|Draft pick within round, i.e. 32nd pick of second round.||
|draft_ovr	|character	|Overall draft pick selection. This can be a little bit patchy, since MFL does not report this number.||
|twitter_username	|character	|Official twitter handle, if known||
|height	|numeric	|height in inches||
|weight	|numeric	|weight in pounds||
|college	|character	|College attended||
|db_season|	numeric|	Year of database build. Previous years may also be available via dynastyprocess.||
|swish_id	|character|	Player ID for Swish Analytics||

In [ ]:
astro_df.index = astro_df.index.astype('int32')
astro_df = astro_df.join(pids_df[['sleeper_id','gsis_id','pfr_id','name']].set_index('sleeper_id'))

In [ ]:
astro_ready_to_join_df = astro_df.loc[:,~astro_df.columns.str.contains('_house.')].drop(columns='name')
astro_ready_to_join_df.to_parquet(path='/content/drive/MyDrive/ff/astro_ready_to_join_df.parquet', compression='snappy')

In [ ]:
pids_df['sleeper_id'] = pids_df['sleeper_id'].fillna(-1).astype('int32').astype('string')
players_df['sleeper_id'] = players_df['player_id'].fillna('NaN').astype('string')

In [ ]:
merged_df = players_df.join(pids_df.set_index('sleeper_id'), on='sleeper_id', lsuffix='_sl', rsuffix='_x')

In [ ]:
merged_df['pfr_id'] = merged_df['pfr_id'].fillna('NaN').astype('string')

In [ ]:
merged_df[(~merged_df['espn_id_x'].isna()) & (merged_df['pfr_id'] == 'NaN')][['espn_id_x','full_name']]

      espn_id_x               full_name
995     14297.0              Ron Parker
2199    17141.0           Kasim Edebali
1284    15369.0            Lance Dunbar
2801  2515962.0          DeAndrew White
4501  3121581.0        Devaroe Lawrence
...         ...                     ...
4401  3052182.0  Damore'ea Stringfellow
6372  3119996.0           Xavier Turner
1834    17435.0          Malcolm Butler
5212  3127274.0       Hercules Mata'afa
1185    15457.0          Travaris Cadet

[1552 rows x 2 columns]

In [ ]:
sorted(merged_df.columns.tolist())

['active',
 'age_sl',
 'age_x',
 'birth_date',
 'birthdate',
 'cbs_id',
 'cfbref_id',
 'college_sl',
 'college_x',
 'competitions',
 'db_season',
 'depth_chart_order',
 'depth_chart_position',
 'draft_ovr',
 'draft_pick',
 'draft_round',
 'draft_year',
 'espn_id_sl',
 'espn_id_x',
 'fantasy_data_id_sl',
 'fantasy_data_id_x',
 'fantasy_positions',
 'fantasypros_id',
 'first_name',
 'fleaflicker_id',
 'full_name',
 'gsis_id_sl',
 'gsis_id_x',
 'hashtag',
 'height_sl',
 'height_x',
 'high_school',
 'injury_body_part',
 'injury_notes',
 'injury_status',
 'ktc_id',
 'last_name',
 'merge_name',
 'metadata',
 'mfl_id',
 'name',
 'news_updated',
 'nfl_id',
 'number',
 'oddsjam_id',
 'pff_id',
 'pfr_id',
 'player_id',
 'position_sl',
 'position_x',
 'rotowire_id_sl',
 'rotowire_id_x',
 'rotoworld_id_sl',
 'rotoworld_id_x',
 'search_first_name',
 'search_full_name',
 'search_last_name',
 'search_rank',
 'sleeper_id',
 'sport',
 'sportradar_id_sl',
 'sportradar_id_x',
 'stats_global_id',
 'stats_id_sl',
 'stats_id_x',
 'status',
 'swish_id_sl',
 'swish_id_x',
 'team_sl',
 'team_x',
 'twitter_username',
 'weight_sl',
 'weight_x',
 'yahoo_id_sl',
 'yahoo_id_x',
 'years_exp']

In [ ]:
pfr_df = merged_df[merged_df['pfr_id'] != 'NaN']

# Next Steps

[x] Use pfr_id to scrape pfr.

old but should work https://github.com/zackthoutt/nfl-player-stats/tree/master

[x] parse the table at the top; get birthdate and place, add both

[ ] coalesce birthdate, preferring pfr.

[x] geopy lookup birthplace -> coordinates

[ ] assume noon for time of birth

[ ] pass that to https://github.com/theriftlab/immanuel-python

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
from numpy.random import default_rng
from time import sleep

#import geocoder

from geopy.geocoders import Nominatim

rng = default_rng()

def get_lat_long_geopy(location):
    """Gets latitude and longitude for a given location using GeoPy.

    Args:
        location (str): The location string (e.g., "Tyler, TX").

    Returns:
        tuple: A tuple containing latitude and longitude (float, float) if successful,
               or (None, None) if there's an error or no results.
    """
    try:
        geolocator = Nominatim(user_agent="fantasy_football_birthplace_lookup")
        g = geolocator.geocode(location, featuretype='city')
        #g = geocoder.osm(location)
        if g:
          return g
        else:
            print(f"GeoPy couldn't find coordinates for location: {location}")
            return None, None
    except Exception as e:
        print(f"Error using GeoPy: {e}")
        return None, None

def birthdate(pfr_id="DextGe00"):
  if pfr_id == 'NaN':
    location = None
    latitude = None
    longitude = None
    return location, latitude, longitude
  time_to_sleep = rng.uniform(5, 8)
  sleep(time_to_sleep)
  print(pfr_id)
  url = f"https://www.pro-football-reference.com/players/{pfr_id[0].upper()}/{pfr_id}.htm"
  response = requests.get(url)
  response.raise_for_status()

  soup = BeautifulSoup(response.content, 'html.parser')

  birth_span = soup.find(id='necro-birth')

  if birth_span:
    birth_date = birth_span.get('data-birth')

    location_match = re.search(r'in\s(.*?)<a href="/friv/birthplaces.*?>(.*?)</a>', str(birth_span))
    if location_match:
        city = location_match.group(1).strip()
        state = location_match.group(2).strip()
        location = f"{city} {state}"
    else:
        location = None
        latitude = None
        longitude = None
    '''
    if location:
      geoloc = get_lat_long_geopy(location)
      if geoloc:
        latitude, longitude = geoloc.latitude, geoloc.longitude
      else:
        latitude = None
        longitude = None
    '''
    #data = {'birth_date': [birth_date], 'birth_place': [location], 'latitude': [latitude], 'longitude': [longitude]}
    #df = pd.DataFrame(data)
    return birth_date, location #, latitude, longitude
  else:
    print("Error: Could not find the element with id='necro-birth' on the page.")
    location = None
    birth_date = None
    return birth_date, location

print(birthdate('LaPoSa01'))

LaPoSa01
('2001-01-12', None)

In [ ]:
pfr_active = pd.read_csv('/content/drive/My Drive/ff/pfr_active.csv', index_col=0)

In [ ]:
pfr_active.loc[8470:]

,rotowire_id_sl,age_sl,college_sl,espn_id_sl,first_name,height_sl,search_full_name,injury_notes,oddsjam_id,yahoo_id_sl,...,draft_round,draft_pick,draft_ovr,twitter_username,height_x,weight_x,college_x,db_season,pfr_birth_date,birth_place
8374,15906.0,25.0,UTSA,NaN,Riq,76,riqwoolen,NaN,14C27BC9E759,NaN,...,5.0,10.0,NaN,NaN,76.0,210.0,UTSA,2024.0,1999-05-02,NaN
8375,16185.0,25.0,UCF,NaN,Kalia,74,kaliadavis,NaN,C22FC7D15DE2,NaN,...,6.0,41.0,220.0,NaN,74.0,310.0,UCF,2024.0,NaN,NaN
8376,16190.0,23.0,UAB,NaN,Alex,77,alexwright,NaN,44303949681F,NaN,...,3.0,14.0,78.0,NaN,77.0,267.0,UAB,2024.0,NaN,NaN
8377,16141.0,25.0,Toledo,NaN,Tycen,74,tycenanderson,NaN,94FF54BBA52E,NaN,...,5.0,23.0,166.0,NaN,74.0,209.0,Toledo,2024.0,NaN,NaN
8380,16124.0,24.0,Stanford,NaN,Thomas,75,thomasbooker,NaN,F4BDCCCD43C9,NaN,...,5.0,7.0,150.0,NaN,75.0,301.0,Stanford,2024.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11510,17000.0,24.0,North Dakota State,NaN,Hunter,73,hunterluepke,NaN,F8CCEC7300BB,NaN,...,NaN,NaN,NaN,NaN,73.0,238.0,North Dakota State,2024.0,NaN,NaN
11512,17181.0,24.0,Mississippi State,NaN,Tyrus,74,tyruswheat,NaN,25C0697C23E1,NaN,...,NaN,NaN,NaN,NaN,74.0,260.0,Mississippi State,2024.0,NaN,NaN
11514,17115.0,24.0,Florida A&M,NaN,Isaiah,76,isaiahland,NaN,F1BD29AD89D5,NaN,...,NaN,NaN,NaN,NaN,76.0,225.0,Florida A&M,2024.0,NaN,NaN
11541,NaN,48.0,LSU,NaN,Chuck,77,chuckwiley,NaN,NaN,NaN,...,3.0,1.0,62.0,NaN,77.0,275.0,LSU,2024.0,NaN,NaN
11553,NaN,52.0,Oregon,NaN,Chad,72,chadcota,NaN,NaN,NaN,...,7.0,1.0,209.0,NaN,73.0,198.0,Oregon,2024.0,NaN,NaN

In [ ]:
"""
for index, row in pfr_active.loc[11046:].iterrows():
  #if row.birth_place == nan:
    pfr_active.at[index, 'pfr_birth_date'], pfr_active.at[index, 'birth_place'] = birthdate(row.pfr_id)
    print(f"NEW!!!!!!!!!: {index}; {row.full_name}; {row.pfr_id}; {pfr_active.at[index, 'birth_place']}")
  #else:
    #print(f"Already done: {index}; {row.full_name}; {row.pfr_id}; {row.birth_place}")
"""

'\nfor index, row in pfr_active.loc[11046:].iterrows():\n  #if row.birth_place == nan:\n    pfr_active.at[index, \'pfr_birth_date\'], pfr_active.at[index, \'birth_place\'] = birthdate(row.pfr_id)\n    print(f"NEW!!!!!!!!!: {index}; {row.full_name}; {row.pfr_id}; {pfr_active.at[index, \'birth_place\']}")\n  #else:\n    #print(f"Already done: {index}; {row.full_name}; {row.pfr_id}; {row.birth_place}")\n'

In [ ]:
#pfr_active.to_csv('/content/drive/My Drive/ff/pfr_active_2.csv')

In [ ]:
#pfr_active[['birth_date','pfr_birth_date','birth_place']].info()

In [ ]:
#pfr_active[pfr_active['birth_place'].isna()]['espn_id_x'].fillna(-1).astype('int32')

In [ ]:
espn_df = pd.read_json("https://sports.core.api.espn.com/v3/sports/football/nfl/athletes?limit=100000000")

In [ ]:
espn_df = pd.DataFrame(espn_df['items'].values.tolist())
espn_df

,id,uid,guid,lastName,fullName,displayName,shortName,jersey,active,firstName,...,displayHeight,age,dateOfBirth,experience,birthPlace,dateOfDeath,hand,middleName,citizenship,nickname
0,4246273,s:20~l:28~a:4246273,64cf2ccf-8d24-d1be-3ff4-d46499bdd9a6,[35],[35],[35],[35],35,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4246281,s:20~l:28~a:4246281,c6323fce-962f-a112-b136-9a4ed1d4282b,[Downed],[Downed],[Downed],[Downed],00,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4246289,s:20~l:28~a:4246289,21d50db4-55e3-a493-d76d-30b5a6786bd5,[Downed],[Downed],[Downed],[Downed],00,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4246247,s:20~l:28~a:4246247,5a011f43-549b-7b35-ad26-bb154b973384,[Touchback],[Touchback],[Touchback],[Touchback],00,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4246272,s:20~l:28~a:4246272,9efe3029-4e1f-8a43-2035-79e7479f251b,[Touchback],[Touchback],[Touchback],[Touchback],00,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18720,16424,s:20~l:28~a:16424,9128af51-f36e-32ba-1fdd-73fcbe2116bc,Zupancic,Mike Zupancic,Mike Zupancic,M. Zupancic,53,False,Mike,...,"6' 5""",34.0,1989-12-14T08:00Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18721,15462,s:20~l:28~a:15462,0d261997-24bf-5dd1-5e66-93272eed1a44,Zusevics,Markus Zusevics,Markus Zusevics,M. Zusevics,76,False,Markus,...,"6' 5""",35.0,1989-04-25T07:00Z,{'years': 3},NaN,NaN,NaN,NaN,NaN,NaN
18722,11317,s:20~l:28~a:11317,5a6c4114-bbc8-7941-f7f2-ebae32be0e09,Zuttah,Jeremy Zuttah,Jeremy Zuttah,J. Zuttah,64,False,Jeremy,...,"6' 4""",38.0,1986-06-01T07:00Z,{'years': 10},"{'city': 'Edison', 'state': 'NJ'}",NaN,NaN,NaN,NaN,NaN
18723,4294520,s:20~l:28~a:4294520,5114b190-78e6-daca-531b-be29d9cb2e72,Zylstra,Brandon Zylstra,Brandon Zylstra,B. Zylstra,13,False,Brandon,...,"6' 2""",31.0,1993-03-25T08:00Z,{'years': 5},"{'city': 'Spicer', 'state': 'MN', 'country': '...",NaN,NaN,NaN,NaN,NaN
18724,4608362,s:20~l:28~a:4608362,c6fc7cc2-71d6-3665-9189-75661a10cdba,Zylstra,Shane Zylstra,Shane Zylstra,S. Zylstra,84,True,Shane,...,"6' 4""",27.0,1996-11-16T08:00Z,{'years': 3},"{'city': 'Spicer', 'state': 'MN', 'country': '...",NaN,NaN,NaN,NaN,NaN

In [ ]:
#espn_df.to_csv('/content/drive/My Drive/ff/espn_df.csv')
#espn_df = pd.read_csv('/content/drive/My Drive/ff/espn_df.csv', index_col=0)

In [ ]:
espn_df[~espn_df['birthPlace'].isna()][['id','fullName','dateOfBirth','birthPlace']]

,id,fullName,dateOfBirth,birthPlace
8,4429202,Israel Abanikanda,2002-10-05T07:00Z,"{'city': 'Brooklyn', 'state': 'NY', 'country':..."
9,16836,Jared Abbrederis,1990-12-17T08:00Z,"{'city': 'West Allis', 'state': 'WI'}"
11,14466,Isa Abdul-Quddus,1989-08-03T07:00Z,"{'city': 'Newark', 'state': 'NJ'}"
12,2576336,Ameer Abdullah,1993-06-13T07:00Z,"{'city': 'Homewood', 'state': 'AL', 'country':..."
13,8645,Hamza Abdullah,1983-08-20T07:00Z,"{'city': 'Los Angeles', 'state': 'CA'}"
...,...,...,...,...
18716,2752,Paul Zukauskas,1979-07-12T07:00Z,"{'city': 'Weymouth', 'state': 'MA'}"
18719,3915123,Jabari Zuniga,1997-08-14T07:00Z,"{'city': 'Marietta', 'state': 'GA', 'country':..."
18722,11317,Jeremy Zuttah,1986-06-01T07:00Z,"{'city': 'Edison', 'state': 'NJ'}"
18723,4294520,Brandon Zylstra,1993-03-25T08:00Z,"{'city': 'Spicer', 'state': 'MN', 'country': '..."
18724,4608362,Shane Zylstra,1996-11-16T08:00Z,"{'city': 'Spicer', 'state': 'MN', 'country': '..."

In [ ]:
espn_df[espn_df['id'].fillna(-1).astype('int32').isin(sorted(set(list(pfr_active[pfr_active['birth_place'].isna()]['espn_id_x'].fillna(-1).astype('int32')))))]['birthPlace'].info()

<class 'pandas.core.series.Series'>
Index: 243 entries, 67 to 18672
Series name: birthPlace
Non-Null Count  Dtype
--------------  -----
237 non-null    object
dtypes: object(1)
memory usage: 3.8+ KB

In [ ]:
#espn_df[espn_df['id'] == "15802"]

In [ ]:
espn_df_2 = espn_df.join(pd.json_normalize(espn_df['birthPlace'])).drop('birthPlace', axis='columns')

In [ ]:
espn_df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18725 entries, 0 to 18724
Data columns (total 25 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             18725 non-null  object
 1   uid            18725 non-null  object
 2   guid           18725 non-null  object
 3   lastName       18725 non-null  object
 4   fullName       18725 non-null  object
 5   displayName    18725 non-null  object
 6   shortName      18725 non-null  object
 7   jersey         15493 non-null  object
 8   active         18725 non-null  bool
 9   firstName      18719 non-null  object
 10  weight         18546 non-null  float64
 11  displayWeight  18546 non-null  object
 12  height         18646 non-null  float64
 13  displayHeight  18646 non-null  object
 14  age            18109 non-null  float64
 15  dateOfBirth    18109 non-null  object
 16  experience     14044 non-null  object
 17  dateOfDeath    74 non-null     object
 18  hand           356 non-null    object
 19  middleName     156 non-null    object
 20  citizenship    8 non-null      object
 21  nickname       3 non-null      object
 22  city           15489 non-null  object
 23  state          15402 non-null  object
 24  country        7896 non-null   object
dtypes: bool(1), float64(3), object(21)
memory usage: 3.4+ MB

In [ ]:
espn_df_2[(~espn_df_2['city'].isna()) | (~espn_df_2['state'].isna()) | (~espn_df_2['country'].isna())]

,id,uid,guid,lastName,fullName,displayName,shortName,jersey,active,firstName,...,dateOfBirth,experience,dateOfDeath,hand,middleName,citizenship,nickname,city,state,country
8,4429202,s:20~l:28~a:4429202,2fcbb6af-36f8-3b49-9438-3fdef938d6da,Abanikanda,Israel Abanikanda,Israel Abanikanda,I. Abanikanda,25,True,Israel,...,2002-10-05T07:00Z,{'years': 2},NaN,NaN,NaN,NaN,NaN,Brooklyn,NY,USA
9,16836,s:20~l:28~a:16836,cda63374-960c-425d-757b-c096ca165ed5,Abbrederis,Jared Abbrederis,Jared Abbrederis,J. Abbrederis,10,False,Jared,...,1990-12-17T08:00Z,{'years': 4},NaN,NaN,NaN,NaN,NaN,West Allis,WI,NaN
11,14466,s:20~l:28~a:14466,355b7a2c-1748-5ced-473a-838baca31f45,Abdul-Quddus,Isa Abdul-Quddus,Isa Abdul-Quddus,I. Abdul-Quddus,24,False,Isa,...,1989-08-03T07:00Z,{'years': 6},NaN,NaN,NaN,NaN,NaN,Newark,NJ,NaN
12,2576336,s:20~l:28~a:2576336,8993c23a-a998-ad6b-19aa-0b50bcaadc73,Abdullah,Ameer Abdullah,Ameer Abdullah,A. Abdullah,8,True,Ameer,...,1993-06-13T07:00Z,{'years': 10},NaN,NaN,NaN,NaN,NaN,Homewood,AL,USA
13,8645,s:20~l:28~a:8645,ca778095-7a84-479f-9c48-3ca08b8a5446,Abdullah,Hamza Abdullah,Hamza Abdullah,H. Abdullah,23,False,Hamza,...,1983-08-20T07:00Z,{'years': 7},NaN,NaN,NaN,NaN,NaN,Los Angeles,CA,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18716,2752,s:20~l:28~a:2752,0ff52d6c-2d11-e7ad-2b68-ba84aedf84be,Zukauskas,Paul Zukauskas,Paul Zukauskas,P. Zukauskas,66,False,Paul,...,1979-07-12T07:00Z,{'years': 4},NaN,NaN,NaN,NaN,NaN,Weymouth,MA,NaN
18719,3915123,s:20~l:28~a:3915123,b9542609-1a89-36d1-6c3f-94b3f06efeb7,Zuniga,Jabari Zuniga,Jabari Zuniga,J. Zuniga,91,True,Jabari,...,1997-08-14T07:00Z,{'years': 4},NaN,NaN,NaN,NaN,NaN,Marietta,GA,USA
18722,11317,s:20~l:28~a:11317,5a6c4114-bbc8-7941-f7f2-ebae32be0e09,Zuttah,Jeremy Zuttah,Jeremy Zuttah,J. Zuttah,64,False,Jeremy,...,1986-06-01T07:00Z,{'years': 10},NaN,NaN,NaN,NaN,NaN,Edison,NJ,NaN
18723,4294520,s:20~l:28~a:4294520,5114b190-78e6-daca-531b-be29d9cb2e72,Zylstra,Brandon Zylstra,Brandon Zylstra,B. Zylstra,13,False,Brandon,...,1993-03-25T08:00Z,{'years': 5},NaN,NaN,NaN,NaN,NaN,Spicer,MN,USA
18724,4608362,s:20~l:28~a:4608362,c6fc7cc2-71d6-3665-9189-75661a10cdba,Zylstra,Shane Zylstra,Shane Zylstra,S. Zylstra,84,True,Shane,...,1996-11-16T08:00Z,{'years': 3},NaN,NaN,NaN,NaN,NaN,Spicer,MN,USA

In [ ]:
#espn_df_2[((espn_df_2['city'].isna()) | (espn_df_2['state'].isna())) & (~espn_df_2['country'].isna())][['city', 'country']]

In [ ]:
birth_df = pd.read_csv('/content/drive/My Drive/ff/birth_df.csv', index_col=0)
birth_df_sm = pd.read_csv('/content/drive/My Drive/ff/birth_df_sm.csv', index_col=0)
merged_df = pd.read_csv('/content/drive/My Drive/ff/merged_df.csv', index_col=0, low_memory=False)
pfr_active = pd.read_csv('/content/drive/My Drive/ff/pfr_active.csv', index_col=0)
pfr_active_2 = pd.read_csv('/content/drive/My Drive/ff/pfr_active_2.csv', index_col=0)
#espn_df = pd.read_csv('/content/drive/My Drive/ff/espn_df.csv', index_col=0)

In [ ]:
states = [
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA",
    "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
    "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
    "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
    "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY",
    "DC"
]

In [ ]:
#list(pfr_active[(~pfr_active['birth_place'].isna()) & (~pfr_active['birth_place'].str[-2:].isin(states))]['birth_place'])

In [ ]:
#pfr_active.replace([' American Samoa', ' Ontario'], ['Pago Pago, American Samoa', 'Toronto, Ontario'], inplace=True)
#pfr_active[(pfr_active['birth_place'] == 'Pago Pago, American Samoa') | (pfr_active['birth_place'] == 'Toronto, Ontario')]

In [ ]:
#espn_df_2 = espn_df

In [ ]:
#espn_df_2.info()

In [ ]:
espn_df_2['birth_place'] = espn_df_2['city'].fillna('') + ', ' + espn_df_2['state'].fillna('') + ', ' + espn_df_2['country'].fillna('')
espn_df_2['birth_place'] = espn_df_2['birth_place'].str.rstrip(", ").str.rstrip(", ").str.rstrip(", ")
espn_df_2['birth_place'] = espn_df_2[espn_df_2['birth_place'] != '']['birth_place'].str.replace(', USA', '').str.lstrip(", ").str.lstrip(", ").str.lstrip(", ").str.replace(', , ', ', ')
espn_df_2['birth_place'] = espn_df_2[espn_df_2['birth_place'] != '']['birth_place'].str.replace(r'^,\s$', '')
espn_df_2['id'] = espn_df_2['id'].fillna(-1).astype('int32')

In [ ]:
#espn_df_2['birth_place'].info()

In [ ]:
#espn_df_2['birth_place']

In [ ]:
#list(espn_df_2[(~espn_df_2['birth_place'].isna()) & (~espn_df_2['birth_place'].str[-2:].isin(states))]['birth_place'])

In [ ]:
"""
merged_df['espn_id_x'] = merged_df['espn_id_x'].fillna(-1).astype('int32')
merged_df[(merged_df['espn_id_x'] > 0)][['espn_id_x','full_name']]
"""

"\nmerged_df['espn_id_x'] = merged_df['espn_id_x'].fillna(-1).astype('int32')\nmerged_df[(merged_df['espn_id_x'] > 0)][['espn_id_x','full_name']]\n"

In [ ]:
merged_df[['full_name', 'number', 'team_x', 'position_x','birthdate','birth_date','active', 'espn_id_x','sleeper_id']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 10552 entries, 6462 to 3992
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   full_name   10552 non-null  object
 1   number      10324 non-null  float64
 2   team_x      5728 non-null   object
 3   position_x  5728 non-null   object
 4   birthdate   5718 non-null   object
 5   birth_date  9725 non-null   object
 6   active      10552 non-null  bool
 7   espn_id_x   4962 non-null   float64
 8   sleeper_id  10552 non-null  float64
dtypes: bool(1), float64(3), object(5)
memory usage: 1010.3+ KB

In [ ]:
merged_df.dropna(subset=['full_name'], inplace=True)
merged_df['sleeper_id'] = merged_df['sleeper_id'].astype('float64')

In [ ]:
espn_df_2[['id','birth_place','dateOfBirth']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18725 entries, 0 to 18724
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           18725 non-null  int32
 1   birth_place  15738 non-null  object
 2   dateOfBirth  18109 non-null  object
dtypes: int32(1), object(2)
memory usage: 365.8+ KB

In [ ]:
pfr_active_2[['sleeper_id','birth_place','birth_date']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 2708 entries, 6 to 11553
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sleeper_id   2708 non-null   int64
 1   birth_place  2361 non-null   object
 2   birth_date   2708 non-null   object
dtypes: int64(1), object(2)
memory usage: 84.6+ KB

In [ ]:
slim_df = merged_df[['full_name', 'number', 'team_x', 'position_x','birthdate','birth_date','active', 'espn_id_x','sleeper_id']].join(espn_df_2[['id','birth_place','dateOfBirth']].set_index('id'), on='espn_id_x', lsuffix='_m', rsuffix='_e').join(pfr_active[['sleeper_id','birth_place','birth_date']].set_index('sleeper_id'), on='sleeper_id', lsuffix='_m', rsuffix='_p')

In [ ]:
slim_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10552 entries, 6462 to 3992
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   full_name      10552 non-null  object
 1   number         10324 non-null  float64
 2   team_x         5728 non-null   object
 3   position_x     5728 non-null   object
 4   birthdate      5718 non-null   object
 5   birth_date_m   9725 non-null   object
 6   active         10552 non-null  bool
 7   espn_id_x      4962 non-null   float64
 8   sleeper_id     10552 non-null  float64
 9   birth_place_m  4691 non-null   object
 10  dateOfBirth    4948 non-null   object
 11  birth_place_p  2127 non-null   object
 12  birth_date_p   2710 non-null   object
dtypes: bool(1), float64(3), object(9)
memory usage: 1.3+ MB

slim_df before cleanup:

```
---  ------         --------------  -----  
 0   full_name      10552 non-null  object
 1   number         10324 non-null  float64
 2   team_x         5728 non-null   object
 3   position_x     5728 non-null   object
 4   birthdate      5718 non-null   object
 5   birth_date_m   9725 non-null   object
 6   active         10552 non-null  bool   
 7   espn_id_x      4962 non-null   float64
 8   sleeper_id     10552 non-null  float64
 9   birth_place_m  4691 non-null   object
 10  dateOfBirth    4948 non-null   object
 11  birth_place_p  2127 non-null   object
 12  birth_date_p   2710 non-null   object
 ```

best birthdates - birth_date_m > birthdate > dateOfBirth > birth_date_p

In [ ]:
slim_df['full_name'].sample(5)

706           Joe Mays
5276      Tyler Hoppes
4995        Ian Thomas
6664    A.J. Ouellette
3850      Louis Palmer
Name: full_name, dtype: object

In [ ]:
slim_df['number'].sample(5)

3812    68.0
4652    64.0
4386    41.0
4960     0.0
3338    19.0
Name: number, dtype: float64

In [ ]:
slim_df['team_x'].sample(5)

7278    NaN
8405    PIT
4622     FA
475      FA
928     NYJ
Name: team_x, dtype: object

In [ ]:
slim_df['position_x'].sample(5)

7558     WR
5948    NaN
2022      S
1695     CB
189      CB
Name: position_x, dtype: object

In [ ]:
slim_df['birthdate'].sample(5)

1374            NaN
1456     1990-07-14
5460     1994-03-16
4204     1994-05-27
11541    1975-07-16
Name: birthdate, dtype: object

In [ ]:
slim_df['birth_date_m'].sample(5)

3047    1993-01-08
4765    1994-12-03
5044    1996-09-30
3945           NaN
8277    1998-08-12
Name: birth_date_m, dtype: object

In [ ]:
slim_df['espn_id_x'].sample(5)

3449           NaN
6378     3913020.0
11036          NaN
8879           NaN
6396     3125402.0
Name: espn_id_x, dtype: float64

In [ ]:
slim_df['sleeper_id'].sample(5)

7747    7747.0
5102    5102.0
1357    1357.0
4140    4140.0
4148    4148.0
Name: sleeper_id, dtype: float64

In [ ]:
slim_df['birth_place_m'].sample(5)

1282             Tampa, FL
4643     Saint Charles, MO
5538                   NaN
8622                   NaN
10212                  NaN
Name: birth_place_m, dtype: object

In [ ]:
slim_df['birth_place_p'].sample(5)

7581         San Antonio, TX
804                      NaN
4357     Fort Lauderdale, FL
5872               Inman, SC
12271                    NaN
Name: birth_place_p, dtype: object

In [ ]:
slim_df['dateOfBirth'].sample(5)

2151   1992-03-18
6285   1995-12-10
2823   1993-01-30
607    1908-06-30
3939   1908-06-30
Name: dateOfBirth, dtype: datetime64[ns]

In [ ]:
slim_df['birth_date_p'].sample(5)

2799           NaN
2313    1992-07-08
5257           NaN
3755           NaN
1134           NaN
Name: birth_date_p, dtype: object

In [ ]:
slim_df['full_name'] = slim_df['full_name'].fillna('None').astype('str')
slim_df['number'] = slim_df['number'].fillna('-1').astype('int8')
slim_df['team_x'] = slim_df['team_x'].fillna('None').astype('str')
slim_df['position_x'] = slim_df['position_x'].fillna('None').astype('str')
slim_df['birthdate'] = slim_df['birthdate'].fillna('1908-06-30').astype('datetime64[ns]')
slim_df['birth_date_m'] = slim_df['birth_date_m'].fillna('1908-06-30').astype('datetime64[ns]')
slim_df['dateOfBirth'] = slim_df['dateOfBirth'].fillna('1908-06-30').astype('datetime64[ns]')
slim_df['birth_date_p'] = slim_df['birth_date_p'].fillna('1908-06-30').astype('datetime64[ns]')
slim_df['espn_id_x'] = slim_df['espn_id_x'].fillna('-1').astype('int32')
slim_df['sleeper_id'] = slim_df['sleeper_id'].fillna('-1').astype('int32')
slim_df['birth_place_m'] = slim_df['birth_place_m'].fillna('None').astype('str')
slim_df['birth_place_p'] = slim_df['birth_place_p'].fillna('None').astype('str')

In [ ]:
slim_df[(~slim_df['birth_place_m'].isna() & (~slim_df['birth_date_m'].isna() | ~slim_df['birthdate'].isna() | ~slim_df['dateOfBirth'].isna()))]

,full_name,number,team_x,position_x,birthdate,birth_date_m,active,espn_id_x,sleeper_id,birth_place_m,dateOfBirth,birth_place_p,birth_date_p
6462,Ellis Richardson,45,None,None,1908-06-30,1995-02-12,True,-1,6462,None,1908-06-30,None,1908-06-30
11255,Nick Amoah,63,None,None,1908-06-30,1908-06-30,True,-1,11255,None,1908-06-30,None,1908-06-30
8842,Malkelm Morrison,0,None,None,1908-06-30,1908-06-30,True,-1,8842,None,1908-06-30,None,1908-06-30
7926,Carl Tucker,0,None,None,1908-06-30,1997-02-06,True,-1,7926,None,1908-06-30,None,1908-06-30
1875,C.J. Mosley,57,NYJ,LB,1992-06-19,1992-06-19,True,16720,1875,"Theodore, AL",1992-06-19,"Theodore, AL",1992-06-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4810,Kwayde Miller,63,None,None,1908-06-30,1993-12-11,True,-1,4810,None,1908-06-30,None,1908-06-30
918,Niles Paul,0,FA,TE,1989-08-09,1989-08-09,False,14156,918,"Omaha, NE",1989-08-09,None,1908-06-30
1591,Alvin Bailey,78,None,None,1908-06-30,1991-08-26,False,-1,1591,None,1908-06-30,None,1908-06-30
6744,Greg Ward,84,FA,WR,1995-07-12,1995-07-12,True,3040035,6744,"Tyler, TX",1995-07-12,"Tyler, TX",1995-07-12
3992,Dave Caldwell,0,None,None,1908-06-30,1908-06-30,False,-1,3992,None,1908-06-30,None,1908-06-30

In [ ]:
#slim_df['dateOfBirth'] = slim_df['dateOfBirth'].str.split(pat="T", n=1, expand=True)[0]

In [ ]:
l23_df = pd.DataFrame.from_dict(league_2023.get_rosters())
l22_df = pd.DataFrame.from_dict(league_2022.get_rosters())
l21_df = pd.DataFrame.from_dict(league_2021.get_rosters())
l20_df = pd.DataFrame.from_dict(league_2020.get_rosters())
l19_df = pd.DataFrame.from_dict(league_2019.get_rosters())
l18_df = pd.DataFrame.from_dict(league_2018.get_rosters())

flat_list = [
    x
    for xs in (l23_df['players'].tolist() + l22_df['players'].tolist() + l21_df['players'].tolist() + l20_df['players'].tolist() + l19_df['players'].tolist() + l18_df['players'].tolist())
    for x in xs
]
players_list_total = sorted(set(flat_list))

In [ ]:
len(players_list_total)

522

In [ ]:
players_list_total

['10222',
 '10225',
 '10229',
 '10236',
 '1034',
 '1038',
 '1048',
 '1049',
 '1052',
 '1067',
 '1071',
 '10859',
 '10937',
 '110',
 '1110',
 '1111',
 '1127',
 '1144',
 '1149',
 '11533',
 '1166',
 '1192',
 '1195',
 '1213',
 '1233',
 '1234',
 '1244',
 '1264',
 '1266',
 '127',
 '1287',
 '1339',
 '1343',
 '1346',
 '1348',
 '1352',
 '1364',
 '1373',
 '138',
 '1386',
 '1387',
 '1408',
 '1426',
 '1433',
 '1466',
 '147',
 '1476',
 '1479',
 '1500',
 '1517',
 '1535',
 '1576',
 '1592',
 '167',
 '1689',
 '17',
 '1706',
 '1793',
 '1817',
 '1825',
 '1833',
 '1837',
 '184',
 '1848',
 '1875',
 '1901',
 '1945',
 '1974',
 '1984',
 '1992',
 '200',
 '2028',
 '2036',
 '2078',
 '2118',
 '2133',
 '2161',
 '2168',
 '2197',
 '2214',
 '2216',
 '2227',
 '223',
 '2238',
 '2251',
 '2257',
 '23',
 '2306',
 '2307',
 '2309',
 '2315',
 '2319',
 '232',
 '2320',
 '2325',
 '2330',
 '2331',
 '2334',
 '2341',
 '2346',
 '2350',
 '2353',
 '2359',
 '2374',
 '2378',
 '2381',
 '2382',
 '2389',
 '2391',
 '2393',
 '24',
 '2410',
 '2431',
 '2449',
 '2460',
 '2476',
 '2505',
 '2583',
 '2617',
 '2677',
 '2711',
 '2747',
 '2749',
 '2822',
 '289',
 '3156',
 '3157',
 '3161',
 '3163',
 '3164',
 '3166',
 '3167',
 '3198',
 '3199',
 '3200',
 '3202',
 '3206',
 '3208',
 '3214',
 '3222',
 '3225',
 '3242',
 '3257',
 '3269',
 '3271',
 '3274',
 '3276',
 '3286',
 '3291',
 '3294',
 '3300',
 '3303',
 '3306',
 '331',
 '3321',
 '3327',
 '333',
 '3399',
 '3415',
 '3423',
 '344',
 '3451',
 '3558',
 '3664',
 '367',
 '3678',
 '391',
 '3969',
 '3973',
 '3976',
 '4017',
 '4018',
 '4029',
 '4033',
 '4034',
 '4035',
 '4036',
 '4037',
 '4039',
 '4040',
 '4046',
 '4055',
 '4063',
 '4066',
 '4068',
 '4070',
 '4071',
 '4075',
 '4077',
 '4080',
 '4081',
 '4082',
 '4089',
 '4098',
 '4109',
 '4110',
 '4111',
 '4118',
 '4131',
 '4137',
 '4144',
 '4146',
 '4149',
 '4150',
 '4152',
 '4157',
 '4158',
 '4171',
 '4177',
 '4195',
 '4199',
 '421',
 '4217',
 '4220',
 '4227',
 '4233',
 '4234',
 '4263',
 '4273',
 '4319',
 '4351',
 '4381',
 '4413',
 '4421',
 '4454',
 '4455',
 '4531',
 '455',
 '4602',
 '4663',
 '4666',
 '4741',
 '4866',
 '4881',
 '4892',
 '49',
 '491',
 '4943',
 '4949',
 '4950',
 '4951',
 '4958',
 '4960',
 '4962',
 '4968',
 '4971',
 '4973',
 '4978',
 '4981',
 '4983',
 '4984',
 '4985',
 '4988',
 '4990',
 '4992',
 '4993',
 '4998',
 '5000',
 '5001',
 '5007',
 '5009',
 '5010',
 '5012',
 '5013',
 '5022',
 '5024',
 '503',
 '5030',
 '5038',
 '5041',
 '5045',
 '5046',
 '5052',
 '5061',
 '5068',
 '5086',
 '5095',
 '5107',
 '5110',
 '5112',
 '5119',
 '5122',
 '5131',
 '5133',
 '5136',
 '515',
 '5170',
 '5185',
 '5209',
 '5230',
 '5248',
 '5272',
 '5284',
 '5332',
 '5334',
 '5346',
 '5347',
 '536',
 '538',
 '5536',
 '5549',
 '5580',
 '560',
 '5655',
 '58',
 '5816',
 '5840',
 '5844',
 '5846',
 '5848',
 '5849',
 '5850',
 '5857',
 '5859',
 '5862',
 '5870',
 '5872',
 '5880',
 '5890',
 '5892',
 '59',
 '5906',
 '5916',
 '5917',
 '5927',
 '5928',
 '5937',
 '5944',
 '5947',
 '5955',
 '5960',
 '5967',
 '5980',
 '5985',
 '5987',
 '5991',
 '5995',
 '6011',
 '6039',
 '6056',
 '6059',
 '6083',
 '6119',
 '6120',
 '6124',
 '6126',
 '6130',
 '6149',
 '6151',
 '616',
 '6208',
 '6220',
 '642',
 '650',
 '6528',
 '6659',
 '6694',
 '676',
 '6768',
 '6770',
 '6781',
 '6783',
 '6786',
 '6790',
 '6794',
 '6797',
 '6801',
 '6803',
 '6804',
 '6806',
 '6807',
 '6813',
 '6814',
 '6819',
 '6820',
 '6824',
 '6826',
 '6828',
 '6845',
 '6847',
 '6853',
 '6869',
 '6880',
 '6886',
 '6904',
 '6908',
 '6918',
 '6938',
 '6943',
 '6945',
 '6949',
 '6955',
 '6984',
 '6996',
 '7002',
 '7016',
 '7023',
 '7042',
 '7045',
 '7062',
 '7086',
 '7090',
 '7117',
 '7523',
 '7525',
 '7526',
 '7528',
 '7543',
 '7547',
 '7553',
 '7561',
 '7564',
 '7569',
 '7571',
 '7588',
 '7591',
 '7594',
 '7596',
 '7600',
 '7601',
 '7607',
 '7608',
 '7610',
 '7611',
 '7640',
 '7648',
 '7670',
 '7839',
 '788',
 '7922',
 '8110',
 '8112',
 '8119',
 '8121',
 '8122',
 '8129',
 '8130',
 '8131',
 '8132',
 '8135',
 '8136',
 '8137',
 '8138',
 '8139',
 '8143',
 '8144',
 '8146',
 '8150',
 '8151',
 '8154',
 '8155',
 '8162',
 '8167',
 '8172',
 '8183',
 '8188',
 '8205',
 '8210',
 '8228',
 '8230',
 '8259',
 '8266',
 '8286',
 '8289',
 '830',
 '8323',
 '8363',
 '8676',
 '899',
 '9221',
 '9224',
 '9226',
 '9228',
 '9229',
 '943',
 '947',
 '9488',
 '9493',
 '9500',
 '9502',
 '9508',
 '9509',
 '9511',
 '954',
 '956',
 '957',
 '96',
 '967',
 '9753',
 '9756',
 '9758',
 '988',
 '9997',
 'ARI',
 'BAL',
 'BUF',
 'CAR',
 'CHI',
 'CIN',
 'CLE',
 'DAL',
 'DEN',
 'DET',
 'GB',
 'HOU',
 'IND',
 'JAX',
 'KC',
 'LAC',
 'LAR',
 'LV',
 'MIA',
 'MIN',
 'NE',
 'NO',
 'PHI',
 'PIT',
 'SEA',
 'SF',
 'TB',
 'TEN',
 'WAS']

In [ ]:
sleepers_active_previously_wo_birthplace = list(slim_df[(slim_df['sleeper_id'].astype('str').isin(players_list_total)) & (slim_df['birth_place_p'] == 'None') & (slim_df['birth_place_m'] == 'None')]['sleeper_id'])

In [ ]:
slim_df[(slim_df['sleeper_id'].astype('str').isin(players_list_total)) & (slim_df['birth_place_p'] == 'None') & (slim_df['birth_place_m'] == 'None')]

Empty DataFrame
Columns: [full_name, number, team_x, position_x, birthdate, birth_date_m, active, espn_id_x, sleeper_id, birth_place_m, dateOfBirth, birth_place_p, birth_date_p]
Index: []

In [ ]:
slim_df.at['11533', 'birth_place_m'] = 'St. Louis, MO'
slim_df.at['9488', 'birth_place_m'] = 'Rockwall, Texas'
slim_df.at['8259', 'birth_place_m'] = 'Hong Kong, China'
slim_df.at['10859', 'birth_place_m'] = 'Highland, IL'
slim_df.at['10937', 'birth_place_m'] = 'Northville, MI'
slim_df.at['9228', 'birth_place_m'] = 'Pasadena, CA'
slim_df.at['10225', 'birth_place_m'] = 'Brandon, MS'
slim_df.at['10229', 'birth_place_m'] = 'North Richland Hills, TX'
slim_df.at['9226', 'birth_place_m'] = 'Missouri City, TX'
slim_df.at['9509', 'birth_place_m'] = 'Tucson, AZ'
slim_df.at['9229', 'birth_place_m'] = ' Miami, FL'
slim_df.at['9221', 'birth_place_m'] = 'Dalton, GA'
slim_df.at['10236', 'birth_place_m'] = 'Las Vegas, NV'
slim_df.at['9508', 'birth_place_m'] = 'Ponchatoula, LA'
slim_df.at['9224', 'birth_place_m'] = 'London, Ontario'
slim_df.at['9500', 'birth_place_m'] = 'Suwanee, GA'
slim_df.at['9997', 'birth_place_m'] = 'Fort Lauderdale, FL'
slim_df.at['9758', 'birth_place_m'] = 'Rancho Cucamonga, CA'
slim_df.at['9502', 'birth_place_m'] = 'Daytona Beach, FL'
slim_df.at['9753', 'birth_place_m'] = 'Camarillo, CA'
slim_df.at['9756', 'birth_place_m'] = 'Frederick, MD'

full_name             Brandon Aubrey
number                            17
team_x                           DAL
position_x                        PK
birthdate        1995-03-14 00:00:00
birth_date_m     1995-03-14 00:00:00
active                          True
espn_id_x                         -1
sleeper_id                     11533
birth_place_m          St. Louis, MO
dateOfBirth      1908-06-30 00:00:00
birth_place_p                   None
birth_date_p     1908-06-30 00:00:00
Name: 11533, dtype: object

In [ ]:
trending_players = players.get_trending_players(sport="nfl", add_drop="add", hours=72, limit=500)
trending_players_df = pd.DataFrame.from_dict(trending_players)
trending_list = list(trending_players_df['player_id'])

In [ ]:
slim_df[(slim_df['sleeper_id'].astype('str').isin(trending_list)) & (slim_df['birth_place_p'] == 'None') & (slim_df['birth_place_m'] == 'None')]

In [ ]:
slim_df.to_csv('/content/drive/My Drive/ff/slim_df.csv')

In [ ]:
slim_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10552 entries, 6462 to 3992
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   full_name      10552 non-null  object
 1   number         10552 non-null  int8
 2   team_x         10552 non-null  object
 3   position_x     10552 non-null  object
 4   birthdate      10552 non-null  datetime64[ns]
 5   birth_date_m   10552 non-null  datetime64[ns]
 6   active         10552 non-null  bool
 7   espn_id_x      10552 non-null  int32
 8   sleeper_id     10552 non-null  int32
 9   birth_place_m  10552 non-null  object
 10  dateOfBirth    10552 non-null  datetime64[ns]
 11  birth_place_p  10552 non-null  object
 12  birth_date_p   10552 non-null  datetime64[ns]
dtypes: bool(1), datetime64[ns](4), int32(2), int8(1), object(5)
memory usage: 1.2+ MB

In [ ]:
s = set(slim_df['sleeper_id'].astype('str'))
s2 = [x for x in players_list_total if x not in s]
s2

['ARI',
 'BAL',
 'BUF',
 'CAR',
 'CHI',
 'CIN',
 'CLE',
 'DAL',
 'DEN',
 'DET',
 'GB',
 'HOU',
 'IND',
 'JAX',
 'KC',
 'LAC',
 'LAR',
 'LV',
 'MIA',
 'MIN',
 'NE',
 'NO',
 'PHI',
 'PIT',
 'SEA',
 'SF',
 'TB',
 'TEN',
 'WAS']

In [ ]:
slim_df[(slim_df['sleeper_id'].astype('str').isin(players_list_total)) &
        ((slim_df['birthdate'] != slim_df['birth_date_m']) |
        (slim_df['birthdate'] != slim_df['birth_date_p']) |
        (slim_df['birth_date_p'] != slim_df['birth_date_m']) |
        (slim_df['birthdate'] != slim_df['dateOfBirth']) |
        (slim_df['dateOfBirth'] != slim_df['birth_date_m']) |
        (slim_df['dateOfBirth'] != slim_df['birth_date_p']))]

,full_name,number,team_x,position_x,birthdate,birth_date_m,active,espn_id_x,sleeper_id,birth_place_m,dateOfBirth,birth_place_p,birth_date_p
11533,Brandon Aubrey,17,DAL,PK,1995-03-14,1995-03-14,True,-1,11533,None,1908-06-30,None,1908-06-30
1195,Doug Martin,22,FA,RB,1989-01-13,1989-01-13,False,14885,1195,"Oakland, CA",1989-01-13,None,1908-06-30
4118,Alex Anzalone,34,DET,LB,1994-01-01,1994-09-22,True,3043107,4118,"Wyomissing, PA",1994-09-22,"Wyomissing, PA",1994-09-22
8136,Rachaad White,1,TBB,RB,1999-04-22,1999-01-12,True,4697815,8136,"Kansas City, MO",1999-01-12,None,1999-01-12
9488,Jaxon Smith-Njigba,11,SEA,WR,2002-02-14,2002-02-14,True,-1,9488,None,1908-06-30,None,2002-02-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8188,Tyquan Thornton,11,NEP,WR,2000-09-07,2000-08-07,True,4362921,8188,"Miami, FL",2000-08-07,None,2000-08-07
4158,Eddie Jackson,39,BAL,S,1992-12-10,1993-12-10,True,3054847,4158,"Lauderdale Lakes, FL",1993-12-10,"Lauderdale Lakes, FL",1993-12-10
7062,Rodrigo Blankenship,15,FA,PK,1997-01-29,1997-01-29,True,3915165,7062,"Marietta, GA",1997-01-29,None,1908-06-30
7922,Riley Patterson,15,WAS,PK,1999-09-07,1999-09-07,True,4243371,7922,"Edwardsville, IL",1999-09-07,None,1908-06-30
4234,Noah Brown,85,HOU,WR,1997-07-19,1996-01-06,True,3121409,4234,"Flanders, NJ",1996-01-06,"Flanders, NJ",1996-01-06

KeyError: Index(['birthdate', 'dateOfBirth', 'birth_date_m', 'birth_date_p'], dtype='object')

In [ ]:
good_df = full_df[['active',
 'age',
 'birth_date_m',
 'birth_date_p',
 'birthdate_m',
 'birthdate_p',
 'dateOfBirth',
 'dateOfDeath',
 'pfr_birth_date',
 'birth_place_m',
 'birth_place_p',
 'citizenship',
 'college_x_m',
 'depth_chart_order_m',
 'depth_chart_position_m',
 'displayHeight',
 'displayName',
 'displayWeight',
 'draft_ovr_m',
 'draft_pick_m',
 'draft_round_m',
 'draft_year_m',
 'espn_id_x_m',
 'experience',
 'fantasy_positions_m',
 'firstName',
 'first_name_m',
 'first_name_p',
 'fullName',
 'full_name_m',
 'hand',
 'height',
 'high_school_m',
 'jersey',
 'lastName',
 'last_name_m',
 'merge_name_m',
 'metadata_m',
 'middleName',
 'name_m',
 'nickname',
 'number_m',
 'position_x_m',
 'search_first_name_m',
 'search_full_name_m',
 'search_last_name_m',
 'search_rank_m',
 'shortName',
 'sleeper_id',
 'status_m',
 'team_x_m',
 'twitter_username_m',
 'weight',
 'years_exp_m']]

In [ ]:
good_df[['active',
 'age',
 'birth_date_m',
 'birth_date_p',
 'birthdate_m',
 'birthdate_p',
 'dateOfBirth',
 'dateOfDeath',
 'pfr_birth_date',
 'birth_place_m',
 'birth_place_p',
 'citizenship',
 'espn_id_x_m',
 'firstName',
 'middleName',
 'lastName',
 'fullName',
 'first_name_m',
 'last_name_m',
 'full_name_m',
 'merge_name_m',
 'metadata_m',
 'name_m',
 'nickname',
 'number_m',
 'position_x_m',
 'search_rank_m',
 'shortName',
 'sleeper_id',
 'status_m',
 'team_x_m',
 'twitter_username_m',
 'weight',
 'years_exp_m']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 10585 entries, 6462 to MIN
Data columns (total 34 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   active              0 non-null      object
 1   age                 4950 non-null   float64
 2   birth_date_m        9725 non-null   object
 3   birth_date_p        0 non-null      object
 4   birthdate_m         5721 non-null   object
 5   birthdate_p         0 non-null      object
 6   dateOfBirth         4950 non-null   object
 7   dateOfDeath         8 non-null      object
 8   pfr_birth_date      0 non-null      object
 9   birth_place_m       4726 non-null   object
 10  birth_place_p       0 non-null      object
 11  citizenship         3 non-null      object
 12  espn_id_x_m         10585 non-null  int32
 13  firstName           4962 non-null   object
 14  middleName          8 non-null      object
 15  lastName            4962 non-null   object
 16  fullName            4962 non-null   object
 17  first_name_m        10585 non-null  object
 18  last_name_m         10585 non-null  object
 19  full_name_m         10553 non-null  object
 20  merge_name_m        5731 non-null   object
 21  metadata_m          7636 non-null   object
 22  name_m              5731 non-null   object
 23  nickname            1 non-null      object
 24  number_m            10326 non-null  float64
 25  position_x_m        5731 non-null   object
 26  search_rank_m       10365 non-null  float64
 27  shortName           4962 non-null   object
 28  sleeper_id          10585 non-null  object
 29  status_m            10542 non-null  object
 30  team_x_m            5731 non-null   object
 31  twitter_username_m  1681 non-null   object
 32  weight              4962 non-null   float64
 33  years_exp_m         10501 non-null  float64
dtypes: float64(5), int32(1), object(28)
memory usage: 3.0+ MB

In [ ]:
dict(espn_df_2[espn_df_2['fullName'] == 'Sam LaPorta'])

{'id': 9647    4430027
 Name: id, dtype: int32,
 'uid': 9647    s:20~l:28~a:4430027
 Name: uid, dtype: object,
 'guid': 9647    c61b32e3-c420-9298-3430-a9fef88819f4
 Name: guid, dtype: object,
 'lastName': 9647    LaPorta
 Name: lastName, dtype: object,
 'fullName': 9647    Sam LaPorta
 Name: fullName, dtype: object,
 'displayName': 9647    Sam LaPorta
 Name: displayName, dtype: object,
 'shortName': 9647    S. LaPorta
 Name: shortName, dtype: object,
 'jersey': 9647    87
 Name: jersey, dtype: object,
 'active': 9647    True
 Name: active, dtype: bool,
 'firstName': 9647    Sam
 Name: firstName, dtype: object,
 'weight': 9647    245.0
 Name: weight, dtype: float64,
 'displayWeight': 9647    245 lbs
 Name: displayWeight, dtype: object,
 'height': 9647    75.0
 Name: height, dtype: float64,
 'displayHeight': 9647    6' 3"
 Name: displayHeight, dtype: object,
 'age': 9647    23.0
 Name: age, dtype: float64,
 'dateOfBirth': 9647    2001-01-12T08:00Z
 Name: dateOfBirth, dtype: object,
 'experience': 9647    {'years': 2}
 Name: experience, dtype: object,
 'dateOfDeath': 9647    NaN
 Name: dateOfDeath, dtype: object,
 'hand': 9647    NaN
 Name: hand, dtype: object,
 'middleName': 9647    NaN
 Name: middleName, dtype: object,
 'citizenship': 9647    NaN
 Name: citizenship, dtype: object,
 'nickname': 9647    NaN
 Name: nickname, dtype: object,
 'city': 9647    Highland
 Name: city, dtype: object,
 'state': 9647    IL
 Name: state, dtype: object,
 'country': 9647    USA
 Name: country, dtype: object,
 'birth_place': 9647    Highland, IL
 Name: birth_place, dtype: object}

In [ ]:
espn_df_2[~espn_df_2['birth_place'].isna()][['id','fullName','jersey','birth_place','dateOfBirth']]

            id           fullName jersey      birth_place        dateOfBirth
8      4429202  Israel Abanikanda     25     Brooklyn, NY  2002-10-05T07:00Z
9        16836   Jared Abbrederis     10   West Allis, WI  1990-12-17T08:00Z
11       14466   Isa Abdul-Quddus     24       Newark, NJ  1989-08-03T07:00Z
12     2576336     Ameer Abdullah      8     Homewood, AL  1993-06-13T07:00Z
13        8645     Hamza Abdullah     23  Los Angeles, CA  1983-08-20T07:00Z
...        ...                ...    ...              ...                ...
18716     2752     Paul Zukauskas     66     Weymouth, MA  1979-07-12T07:00Z
18719  3915123      Jabari Zuniga     91     Marietta, GA  1997-08-14T07:00Z
18722    11317      Jeremy Zuttah     64       Edison, NJ  1986-06-01T07:00Z
18723  4294520    Brandon Zylstra     13       Spicer, MN  1993-03-25T08:00Z
18724  4608362      Shane Zylstra     84       Spicer, MN  1996-11-16T08:00Z

[15802 rows x 5 columns]

In [ ]:
merged_df['number'] = merged_df['number'].fillna(-1).astype('int32')
espn_df_2['jersey'] = espn_df_2['jersey'].fillna(-1).astype('int32')

In [ ]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10585 entries, 6462 to MIN
Data columns (total 76 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   yahoo_id_sl           6756 non-null   float64
 1   fantasy_data_id_sl    7468 non-null   float64
 2   birth_date            9725 non-null   object
 3   search_full_name      10553 non-null  object
 4   news_updated          6758 non-null   float64
 5   active                10585 non-null  bool
 6   rotowire_id_sl        8982 non-null   float64
 7   sport                 10585 non-null  object
 8   oddsjam_id            3503 non-null   object
 9   number                10585 non-null  int32
 10  injury_body_part      686 non-null    object
 11  search_last_name      10553 non-null  object
 12  swish_id_sl           5252 non-null   float64
 13  injury_status         763 non-null    object
 14  sportradar_id_sl      10483 non-null  object
 15  status                10542 non-null  object
 16  espn_id_sl            6742 non-null   float64
 17  college_sl            10259 non-null  object
 18  search_first_name     10553 non-null  object
 19  rotoworld_id_sl       2033 non-null   float64
 20  first_name            10585 non-null  object
 21  weight_sl             10539 non-null  object
 22  player_id             10585 non-null  object
 23  injury_notes          120 non-null    object
 24  last_name             10585 non-null  object
 25  years_exp             10501 non-null  float64
 26  metadata              7636 non-null   object
 27  competitions          10553 non-null  object
 28  height_sl             10540 non-null  object
 29  team_sl               3225 non-null   object
 30  high_school           9049 non-null   object
 31  search_rank           10365 non-null  float64
 32  age_sl                9726 non-null   float64
 33  stats_id_sl           2984 non-null   float64
 34  position_sl           10345 non-null  object
 35  gsis_id_sl            3896 non-null   object
 36  hashtag               10553 non-null  object
 37  depth_chart_order     1727 non-null   float64
 38  fantasy_positions     10286 non-null  object
 39  depth_chart_position  2999 non-null   object
 40  full_name             10553 non-null  object
 41  sleeper_id            10585 non-null  string
 42  mfl_id                5731 non-null   float64
 43  sportradar_id_x       5714 non-null   object
 44  fantasypros_id        4298 non-null   float64
 45  gsis_id_x             4276 non-null   object
 46  pff_id                3419 non-null   float64
 47  nfl_id                1963 non-null   object
 48  espn_id_x             10585 non-null  int32
 49  yahoo_id_x            5301 non-null   float64
 50  fleaflicker_id        520 non-null    float64
 51  cbs_id                5489 non-null   float64
 52  pfr_id                10585 non-null  string
 53  cfbref_id             2844 non-null   object
 54  rotowire_id_x         5721 non-null   float64
 55  rotoworld_id_x        3756 non-null   float64
 56  ktc_id                463 non-null    float64
 57  stats_id_x            5700 non-null   float64
 58  stats_global_id       5731 non-null   float64
 59  fantasy_data_id_x     4348 non-null   float64
 60  swish_id_x            3323 non-null   float64
 61  name                  5731 non-null   object
 62  merge_name            5731 non-null   object
 63  position_x            5731 non-null   object
 64  team_x                5731 non-null   object
 65  birthdate             5721 non-null   object
 66  age_x                 5721 non-null   float64
 67  draft_year            5731 non-null   float64
 68  draft_round           3363 non-null   float64
 69  draft_pick            3362 non-null   float64
 70  draft_ovr             3130 non-null   float64
 71  twitter_username      1681 non-null   object
 72  height_x              5726 non-null   float64
 73  weight_x              5731 non-null   float64
 74  college_x             5723 non-null   object
 75  db_season             5731 non-null   float64
dtypes: bool(1), float64(33), int32(2), object(38), string(2)
memory usage: 6.3+ MB

In [ ]:
new_df = pd.merge(
    left=merged_df[['birth_date','full_name','number','sleeper_id','espn_id_x','pfr_id']],
    right=espn_df_2.rename(columns={'fullName': 'full_name', 'jersey': 'number', 'dateOfBirth': 'birth_date_e'}),
    how='left',
    left_on=['full_name', 'number'],
    right_on=['full_name', 'number'],
)
new_df['birth_place'] = new_df['birth_place'].fillna('NaN').astype('str')
new_df['birth_date_e'] = new_df['birth_date_e'].str.split(pat="T", n=1, expand=True)[0]

In [ ]:
new_df['birth_place'] = new_df['birth_place'].fillna('NaN').astype('str')

In [ ]:
birth_df = new_df[(new_df['birth_place'] != 'NaN') & (new_df['sleeper_id'] != 'NaN')][['id','birth_place','full_name','number','birth_date_e','birth_date','sleeper_id','espn_id_x']]

In [ ]:
birth_df['id'] = birth_df['id'].fillna(-1).astype('int32')
birth_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6338 entries, 0 to 10574
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            6338 non-null   int32
 1   birth_place   6338 non-null   object
 2   full_name     6338 non-null   object
 3   number        6338 non-null   int32
 4   birth_date_e  6225 non-null   object
 5   birth_date    6264 non-null   object
 6   sleeper_id    6338 non-null   string
 7   espn_id_x     6338 non-null   int32
dtypes: int32(3), object(4), string(1)
memory usage: 629.4+ KB

In [ ]:
birth_df.to_csv('/content/drive/My Drive/ff/birth_df.csv')

In [ ]:
birth_df['birth_date_e'] = birth_df['birth_date_e'].fillna('None').astype('str')
birth_df['birth_date'] = birth_df['birth_date'].fillna('None').astype('str')

In [ ]:
smol_df = birth_df[(birth_df['birth_date_e'] != birth_df['birth_date'])]
smol_df[(smol_df['birth_date'] != 'None') & (smol_df['birth_date_e'] != 'None')]
smol_df.to_csv('/content/drive/My Drive/ff/birth_df_sm.csv')

NameError: name 'birth_df' is not defined

In [ ]:
import pandas as pd
birth_df = pd.read_csv('/content/drive/My Drive/ff/birth_df.csv')
smol_df = pd.read_csv('/content/drive/My Drive/ff/birth_df_sm.csv', index_col=False)

In [ ]:
smol_df['birth_place'] = smol_df['birth_place'].fillna('NaN').astype('str')
smol_df[~smol_df['birth_place'].str.contains(',')]

,Unnamed: 0.1,Unnamed: 0,id,birth_place,full_name,number,birth_date_e,birth_date,sleeper_id,espn_id_x
4,213,343,15024,Germany,Markus Kuhn,94,1986-05-05,1989-05-05,1163,15024
8,262,420,3909004,NaN,Taryn Christion,5,1997-02-06,NaN,6489,-1
146,2447,4090,12567,Germany,Brandon Gibson,13,1987-08-13,1987-08-31,496,12567
148,2457,4107,4607264,NaN,Josh Gable,5,NaN,NaN,6754,-1
158,2657,4453,3039738,Haiti,Brisly Estime,3,NaN,1992-12-10,4434,-1
294,4821,8061,4034967,NaN,Jachai Polite,95,1998-03-30,1997-03-30,5851,4034967

In [ ]:
smol_df.drop([4,8,146,148,158,294], inplace=True)

In [ ]:
smol_df[~smol_df['birth_place'].str.contains(',')]

Empty DataFrame
Columns: [Unnamed: 0.1, Unnamed: 0, id, birth_place, full_name, number, birth_date_e, birth_date, sleeper_id, espn_id_x]
Index: []

smol_df is a subset where birth_date and birth_date_e don't match. :(

In [ ]:
smol_df.to_csv('/content/drive/My Drive/ff/birth_df_sm.csv')

In [ ]:
birth_df

,Unnamed: 0,id,birth_place,full_name,number,birth_date_e,birth_date,sleeper_id,espn_id_x
0,0,3926590,"Atlanta, GA",Ellis Richardson,45,1995-02-12,1995-02-12,6462,-1
1,4,16720,"Theodore, AL",C.J. Mosley,57,1992-06-19,1992-06-19,1875,16720
2,7,15825,"Reynoldsburg, OH",Le'Veon Bell,6,1992-02-18,1992-02-18,1408,15825
3,8,3916588,"Traverse City, MI",Matt Seybert,41,NaN,1997-05-02,8074,-1
4,9,10613,"Tallahassee, FL",William Gay,25,1985-01-01,1985-01-01,156,10613
...,...,...,...,...,...,...,...,...,...
6333,10565,4036261,"Pembroke Pines, FL",Devin Bush,30,1998-07-18,1998-07-18,5843,4036261
6334,10566,15457,"Miami, FL",Travaris Cadet,38,1989-02-01,1989-02-01,1185,15457
6335,10570,16091,"Orlando, FL",Quincy McDuffie,16,1990-09-24,1990-09-24,4910,-1
6336,10573,16044,"Broken Arrow, OK",Alvin Bailey,78,1991-08-26,1991-08-26,1591,-1
6337,10574,3040035,"Tyler, TX",Greg Ward,84,1995-07-12,1995-07-12,6744,3040035

In [ ]:
import pandas as pd
birthloc_df = pd.read_csv('/content/drive/My Drive/ff/birthloc_df.csv', index_col=0, parse_dates=True, dtype={'number':'int8', 'espn_id_x':'int32','sleeper_id':'int32'}).rename(columns={'team_x':'team', 'position_x':'position','espn_id_x':'espn_id','birth_place_m':'birthplace' })
#astro_df = pd.read_csv('/content/drive/My Drive/ff/astro_df.csv', index_col=0)

<ipython-input-8-b003cede7d6b>:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  birthloc_df = pd.read_csv('/content/drive/My Drive/ff/birthloc_df.csv', index_col=0, parse_dates=True, dtype={'number':'int8', 'espn_id_x':'int32','sleeper_id':'int32'}).rename(columns={'team_x':'team', 'position_x':'position','espn_id_x':'espn_id','birth_place_m':'birthplace' })

In [ ]:
pip install timezonefinder

Collecting timezonefinder
  Downloading timezonefinder-6.5.2-cp310-cp310-manylinux_2_17_x86_64.manylinux_2_5_x86_64.manylinux1_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: cffi<2,>=1.15.1 in /usr/local/lib/python3.10/dist-packages (from timezonefinder) (1.17.0)
Collecting h3<4,>=3.7.6 (from timezonefinder)
  Downloading h3-3.7.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.10/dist-packages (from timezonefinder) (1.26.4)
Requirement already satisfied: setuptools>=65.5 in /usr/local/lib/python3.10/dist-packages (from timezonefinder) (71.0.4)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi<2,>=1.15.1->timezonefinder) (2.22)
Downloading timezonefinder-6.5.2-cp310-cp310-manylinux_2_17_x86_64.manylinux_2_5_x86_64.manylinux1_x86_64.manylinux2014_x86_64.whl (49.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.4/49.4 MB 13.1 MB/s eta 0:00:00
Downloading h3-3.7.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 52.8 MB/s eta 0:00:00
Installing collected packages: h3, timezonefinder
Successfully installed h3-3.7.7 timezonefinder-6.5.2

In [ ]:
from timezonefinder import TimezoneFinder

tf = TimezoneFinder()
birthloc_df['birthtime'] = "12:00"
birthloc_df['birthtime_true'] = False
birthloc_df['timezone'] = birthloc_df.apply(lambda row: tf.timezone_at(lat=row['latitude'], lng=row['longitude']), axis=1)

In [ ]:
birthloc_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4775 entries, 1 to 9997
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   full_name       4775 non-null   object
 1   number          4775 non-null   int8
 2   team            4775 non-null   object
 3   position        4775 non-null   object
 4   birthdate       4775 non-null   object
 5   active          4775 non-null   bool
 6   espn_id         4775 non-null   int32
 7   sleeper_id      4775 non-null   int32
 8   birthplace      4775 non-null   object
 9   latitude        4775 non-null   float64
 10  longitude       4775 non-null   float64
 11  birthtime       4775 non-null   object
 12  birthtime_true  4775 non-null   bool
 13  timezone        4775 non-null   object
dtypes: bool(2), float64(2), int32(2), int8(1), object(7)
memory usage: 553.4+ KB

In [ ]:
birthloc_df['birthdate'] = birthloc_df['birthdate'].astype('datetime64[ns]')

In [ ]:
pip install kerykeion

Collecting kerykeion
  Downloading kerykeion-4.14.7-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: pydantic<3.0,>=2.5 in /usr/local/lib/python3.10/dist-packages (from kerykeion) (2.8.2)
Collecting pyswisseph<3.0.0.0,>=2.10.3.1 (from kerykeion)
  Downloading pyswisseph-2.10.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.9 kB)
Collecting pytz<2023.0,>=2022.7 (from kerykeion)
  Downloading pytz-2022.7.1-py2.py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.10/dist-packages (from kerykeion) (2.32.3)
Collecting requests-cache<2.0.0,>=1.2.1 (from kerykeion)
  Downloading requests_cache-1.2.1-py3-none-any.whl.metadata (9.9 kB)
Collecting scour<0.39.0,>=0.38.2 (from kerykeion)
  Downloading scour-0.38.2.tar.gz (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.9/52.9 kB 2.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting terminaltables<4.0.0,>=3.1.10 (from kerykeion)
  Downloading terminaltables-3.1.10-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3.0,>=2.5->kerykeion) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in /usr/local/lib/python3.10/dist-packages (from pydantic<3.0,>=2.5->kerykeion) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from pydantic<3.0,>=2.5->kerykeion) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->kerykeion) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->kerykeion) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->kerykeion) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->kerykeion) (2024.7.4)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.10/dist-packages (from requests-cache<2.0.0,>=1.2.1->kerykeion) (24.2.0)
Collecting cattrs>=22.2 (from requests-cache<2.0.0,>=1.2.1->kerykeion)
  Downloading cattrs-23.2.3-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests-cache<2.0.0,>=1.2.1->kerykeion) (4.2.2)
Collecting url-normalize>=1.4 (from requests-cache<2.0.0,>=1.2.1->kerykeion)
  Downloading url_normalize-1.4.3-py2.py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from scour<0.39.0,>=0.38.2->kerykeion) (1.16.0)
Requirement already satisfied: exceptiongroup>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from cattrs>=22.2->requests-cache<2.0.0,>=1.2.1->kerykeion) (1.2.2)
Downloading kerykeion-4.14.7-py3-none-any.whl (314 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 314.9/314.9 kB 7.4 MB/s eta 0:00:00
Downloading pyswisseph-2.10.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 20.9 MB/s eta 0:00:00
Downloading pytz-2022.7.1-py2.py3-none-any.whl (499 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 499.4/499.4 kB 34.1 MB/s eta 0:00:00
Downloading requests_cache-1.2.1-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.4/61.4 kB 5.2 MB/s eta 0:00:00
Downloading terminaltables-3.1.10-py2.py3-none-any.whl (15 kB)
Downloading cattrs-23.2.3-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 4.4 MB/s eta 0:00:00
Downloading url_normalize-1.4.3-py2.py3-none-any.whl (6.8 kB)
Building wheels for collected packages: scour
  Building wheel for scour (setup.py) ... done
  Created wheel for scour: filename=scour-0.38.2-py3-none-any.whl size=54249 sha256=442b9ab40659fd4efa1e6d06ded98d8d9fcff4882389fc15462afe2d9b7b3313
  Stored in directory: /root/.cache/pip/wheels/84/78/74/235abc82aa043a4db23338b7c491a44a20ee824db6710de1fd
Successfully built scour
Installing collected packages: pytz, url-normalize, terminaltables, scour, pyswisseph, cattrs, requests-cache, kerykeion
  Attempting uninstall: pytz
    Found existing installation: pytz 2024.1
    Uninstalling pytz-2024.1:
      Successfully uninstalled pytz-2024.1
Successfully installed cattrs-23.2.3 kerykeion-4.14.7 pyswisseph-2.10.3.2 pytz-2022.7.1 requests-cache-1.2.1 scour-0.38.2 terminaltables-3.1.10 url-normalize-1.4.3

In [ ]:
from kerykeion import AstrologicalSubject, KerykeionChartSVG
import base64

def astro(name, birthdate, birthtime, team, number, position, bt, lat, lng, tz_str, chart=False, online=False, debug=False):
  print(name)
  planets = ['sun',
             'moon',
             'mercury',
             'venus',
             'mars',
             'jupiter',
             'saturn',
             'uranus',
             'neptune',
             'pluto',
             'true_node',
             'mean_node',
             'chiron',
             'mean_lilith']

  houses = ['first_house',
            'second_house',
            'third_house',
            'fourth_house',
            'fifth_house',
            'sixth_house',
            'seventh_house',
            'eighth_house',
            'ninth_house',
            'tenth_house',
            'eleventh_house',
            'twelfth_house']

  k = planets + houses
  y, m, d = birthdate.timetuple()[:3]
  if bt:
    bt = '⌖'
  else:
    bt = '◌'
  hr, mn = birthtime.split(":")[:2]
  hr, mn = int(hr), int(mn)
  a = AstrologicalSubject(name, y, m, d, hr, mn, city=f'{team}-{number}-{position} {bt}', lat=lat, lng=lng, nation='NFL', tz_str=tz_str, online=False)
  astro_dict = dict
  if debug == True:
    return a
  if chart == False:
    return dict((key, dict(a[key])) for key in k)
  if chart == True:
    c = base64.b64encode(KerykeionChartSVG(a).makeTemplate(minify=True).encode('utf-8'))
    _ = dict((key, dict(a[key])) for key in k)
    _['chart'] = c
    return _

In [ ]:
sherm_series = birthloc_df.loc[996]

full_name             Richard Sherman
number                              5
team                               FA
position                           CB
birthdate                  1988-03-30
active                           True
espn_id                         14086
sleeper_id                        996
birthplace                Compton, CA
latitude                    33.894927
longitude                 -118.226624
birthtime                       12:00
birthtime_true                  False
timezone          America/Los_Angeles
Name: 996, dtype: object

In [ ]:
sherm_series = birthloc_df.loc[996]
a = astro(name=sherm_series['full_name'], birthdate=sherm_series['birthdate'], birthtime=sherm_series['birthtime'], team=sherm_series['team'], number=sherm_series['number'], position=sherm_series['position'], bt=sherm_series['birthtime_true'], lat=sherm_series['latitude'], lng=sherm_series['longitude'], tz_str=sherm_series['timezone'], chart=True, debug=False)
#a = astro(name=sherm_series['full_name'], birthdate=sherm_series['birthdate'], birthtime=sherm_series['birthtime'], team=sherm_series['team'], number=sherm_series['number'], position=sherm_series['position'], bt=sherm_series['birthtime_true'], lat=sherm_series['latitude'], lng=sherm_series['longitude'], tz_str=sherm_series['timezone'], chart=False, debug=True)

In [ ]:
pd.json_normalize(a)

,chart,sun.name,sun.quality,sun.element,sun.sign,sun.sign_num,sun.position,sun.abs_pos,sun.emoji,sun.point_type,...,twelfth_house.quality,twelfth_house.element,twelfth_house.sign,twelfth_house.sign_num,twelfth_house.position,twelfth_house.abs_pos,twelfth_house.emoji,twelfth_house.point_type,twelfth_house.house,twelfth_house.retrograde
0,b'PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nVVRG...,Sun,Cardinal,Fire,Ari,0,10.331287,10.331287,♈️,Planet,...,Mutable,Air,Gem,2,22.057467,82.057467,♊️,House,None,None

In [ ]:
import numpy as np
birthloc_df['astro'] = np.nan

In [ ]:
birthloc_df['astro'] = birthloc_df.apply(lambda r: astro(name=r['full_name'], birthdate=r['birthdate'], birthtime=r['birthtime'], team=r['team'], number=r['number'], position=r['position'], bt=r['birthtime_true'], lat=r['latitude'], lng=r['longitude'], tz_str=r['timezone'], chart=True, debug=False)
 , axis=1)

GJ Kinne
Stephen Tulloch
Charles Woodson
Albert McClellan
Tyler Clutts
Damon Cromartie-Smith
Trindon Holliday
Ben Tate
D'Anthony Smith
Mitch Unrein
Kevin Brock
Donald Butler
Bryan Walters
Jameel McClain
Phillip Hunt
Doug Worthington
Richie Brockel
Jed Collins
Tom Johnson
Ronald Talley
Brandon Browner
Josh Brown
Terrelle Pryor
Jayden Reed
Jonathan Mingo
Rashee Rice
Dalton Kincaid
Ross Ventrone
Brandon Boykin
Bryce Brown
Fletcher Cox
Vinny Curry
Nick Foles
Matt Forte
Damaris Johnson
Mychal Kendricks
Chris Polk
Brandon Bolden
Nate Ebner
Marcus Forston
Dont'a Hightower
Chandler Jones
Tavon Wilson
Donnie Avery
Nigel Bradham
Ron Brooks
Tank Carder
Stephon Gilmore
Trevor Graham
Rishard Matthews
Kelcie McCray
Lamar Miller
Ryan Tannehill
Brandon Carr
Marcus Thigpen
Quinton Coples
Demario Davis
Damon Harrison
Stephen Hill
Asa Jackson
Ishmaa'ily Kitchen
Bobby Rainey
Jo-Lonn Dunbar
Tommy Streeter
Deonte Thompson
DeAngelo Tyson
Courtney Upshaw
Vontaze Burfict
Orson Charles
George Iloka
Marvin Jones
Dre Kirkpatrick
Shaun Prater
Calvin Pace
Mohamed Sanu
Devon Still
Taylor Thompson
Emmanuel Acho
Johnson Bademosi
Travis Benjamin
L.J. Fort
Tashaun Gipson
Steve Johnson
John Hughes
James-Michael Johnson
Trent Richardson
Trevin Wade
Brandon Weeden
Sam LaPorta
Billy Winn
Malik Cunningham
Matt Landers
Drew Butler
Danny Lansanah
Robert Golden
Brian Branch
David Paulson
Sydney Brown
Sean Spence
Drew Sanders
Zach Brown
Jake Moody
Mike Martin
Cameron Young
Coty Sensabaugh
Dylan Horton
Scott Solomon
Kendall Wright
BJ Thompson
Daniel Scott
Randy Bullock
Jerrick Reed
Garrett Hartley
Stephen Gostkowski
Jared Crick
Ameer Speed
Christian Braswell
Keshawn Martin
Whitney Mercilus
DJ Ivey
DeVier Posey
Colton Dowell
Dwayne Allen
Vick Ballard
Coby Fleener
NaJee Thompson
Jack Podlesny
Jerrell Freeman
Chandler Harnish
Marcedes Lewis
T.Y. Hilton
Andrew Luck
Matt Overton
Bryan Anger
Jaray Jenkins
Justin Blackmon
Antwon Blake
Andre Branch
Mike Harris
Brandon Marshall
Andy Lee
Julian Stanford
Omar Bolden
Aaron Brewer
Ronnie Hillman
Isaiah Winstead
Jacob Saylors
Malik Jackson
Steven Johnson
Brock Osweiler
Danny Trevathan
Hassan Hall
Derek Wolfe
Dyontae Johnson
Cyrus Gray
Dontari Poe
Devon Wylie
Christo Bilukidi
Jack Crawford
Juron Criner
Rod Streater
Ladarius Green
Todd Herremans
Melvin Ingram
Kendall Reyes
Cole Beasley
Morris Claiborne
Tyrone Crawford
James Hanna
Drake Thomas
Dylan Drummond
Kyle Wilber
Alshon Jeffery
Bryan Thompson
Cullen Loeffler
Shea McClellin
Ryan Quigley
Evan Rodriguez
Brandon Aubrey
Jake Bates
Ryan Broyles
Jonte Green
Devin Leary
Joe Milton
Michael Penix
Chris Greenwood
Caleb Williams
Bo Nix
Drake Maye
J.J. McCarthy
Jayden Daniels
Jordan Travis
Blake Watson
Travis Lewis
Rasheen Ali
Isaiah Davis
Ray Davis
Braelon Allen
Will Shipley
Audric Estime
Kellen Moore
Dillon Johnson
MarShawn Lloyd
Jonathon Brooks
Blake Corum
Trey Benson
Jase McClellan
Erick All
Jared Wiley
Ben Sinnott
Theo Johnson
Tahir Whitehead
AJ Barner
Brock Bowers
Will Hill
Malik Washington
Ainias Smith
Malachi Corley
Jalen McMillan
Ja'Lynn Polk
Jayron Hosley
Rome Odunze
Jordan Whittington
Xavier Worthy
Adonai Mitchell
Troy Franklin
Marvin Harrison
Devontez Walker
Markus Kuhn
Brian Thomas
Ladd McConkey
Keon Coleman
Ricky Pearsall
Rueben Randle
Jermaine Burton
Jaylen Wright
Javon Baker
Jalen Coker
Kimani Vidal
Kedon Slovis
Adrien Robinson
Darius Robinson
Kirk Cousins
Terrion Arnold
Quinyon Mitchell
Chop Robinson
Jared Verse
Dallas Turner
Richard Crawford
Tyler Nubin
Kool-Aid McKinstry
Mike Sainristil
Braden Fiske
Cooper DeJean
Chris Braswell
Cole Bishop
Javon Bullard
Edgerrin Cooper
Kris Jenkins
Ennis Rakestraw
Robert Griffin
T'Vondre Sweat
Mike Hall
Max Melton
Marshawn Kneeland
Ruke Orhorhoro
Maason Smith
Jer'Zhan Newton
Rashean Mathis
Alfred Morris
Dru Phillips
Junior Colson
Jalyx Hunt
Tykee Smith
DeWayne Carter
Keenan Robinson
Calen Bullock
Ty'Ron Hopper
Jonah Elliss
Elijah Jones
Bralen Trice
Adisa Isaac
Jarrian Jones
Kamren Kinchens
Payton Wilson
Jaden Hicks
Jarrett Boykin
T.J. Tampa
Tory Taylor
Tyrice Knight
Jordan Jefferson
Evan Williams
Mike Daniels
Brandon Dorlus
Khyree Jackson
Cedric Gray
Justin Eboigbe
Dadrion Taylor-Demerson
Bub Means
Casey Hayward
Brennan Jackson
Jeremiah Trotter
Nehemiah Pritchett
Mohamed Kamara
Qwan'tez Stiggers
Edefuan Ulofoshio
Javon Solomon
Dezman Moses
Austin Booker
Anthony Gould
Kitan Oladapo
Nick Perry
JD Bertrand
Chau Smith-Wade
Daequan Hardy
Ryan Flournoy
Cedric Johnson
Kamal Hadden
Joshua Karty
Jerel Worthy
Patrick McMorris
Zion Logue
Tyler Davis
Sebastian Janikowski
Frank Alexander
D.J. James
Casey Washington
Darius Muasau
Luke Kuechly
Josh Norman
Devin Culp
Tahj Washington
Jaylen Key
Travaris Cadet
Akiem Hicks
Zach Heins
Lideatrick Griffin
Nick Toon
Mason Tipton
James Anderson
Tyrunn Walker
Kyle Sheets
Ty James
Dallas Gant
Corey White
Lavonte David
Terique Owens
Najee Goode
Leonard Johnson
Isaiah Wooden
Marcus Rosemy-Jacksaint
Austin Jones
Doug Martin
Beau Brade
Keith Tandy
Xavier Johnson
Michael Brockers
Matt Conrath
D.J. Williams
Matt Daniels
Kalen DeLoach
Adam Vinatieri
Austin Davis
Jack Browning
Chris Givens
Harrison Mevis
Johnny Hekker
Tyler Harrell
Janoris Jenkins
Leonard Taylor
Trumaine Johnson
Jack Westover
Rodney McLeod
Maema Njongmeta
Isaiah Pead
Mason Pline
Quinton Pointer
McCallan Castles
Brian Quick
Aidan Robbins
Robert Blanton
LeRon McClain
Audie Cole
Rhett Ellison
Levelle Bailey
Harrison Smith
Steele Chambers
Drake Stoops
Kenny Logan
Blair Walsh
Jarius Wright
Justin Bethel
Pheldarius Payne
Jamell Fleming
Michael Floyd
Miles Austin
Ryan Lindley
Cole Burgess
Austin Stogner
David White
Garrett Celek
Darius Fleming
Easton Gibbs
LaMichael James
AJ Jenkins
Trenton Robinson
Jaye Howard
Jeremy Lane
Greg Scruggs
Robert Turbin
Bobby Wagner
Russell Wilson
Jorvorskie Lane
David Martin-Robinson
Joe Banyard
Dominique Davis
Josh Harris
Jude McAtamney
Jonathan Massaquoi
Ramon Jefferson
Winston Guy
Bruce Irvin
Gable Steveson
David Wallis
J.R. Sweezy
Josh Gordon
Beau Brinkley
Dominique Jones
Griff Whalen
Terrell Manning
Calais Campbell
Will Johnson
Alameda Ta'amu
Jeris Pendleton
Marquette King
Josh Robinson
Mark Barron
Michael Egnew
Derrick Shelby
Olivier Vernon
Marcel Reece
Josh Bush
Alex Tanney
Bernard Pierce
Justin Tucker
Daryl Richardson
Greg Zuerlein
Matt Bryant
Brandon Thompson
Donnie Jones
Craig Robertson
Gerell Robinson
Jonathan Grimes
Nathan Palmer
Chris Lewis-Harris
Duke Ihenacho
Orie Lemon
Vincent Jackson
DeAndre Presley
Ryan Davis
Neiko Thorpe
Lance Dunbar
Josh Kaddu
Antonio Allen
Kai Forbath
Lawrence Guy
Nate Chandler
Kroy Biermann
Jermaine Kearse
Emmanuel Lamur
Robert Hughes
Jeremy Stewart
Josh Chapman
Cory Harkey
Marshall McFadden
Anthony Levine
Kyle Miller
Sam Koch
Eric Weems
Kaelin Burnett
Kyle Nelson
Michael Wilhoite
James Develin
Collin Mooney
Patrick DiMarco
Jeremy Ross
Dan Herron
Jamize Olawale
DeShawn Shead
Josh Bellamy
Michael Preston
Brad Smelley
Brandon Barden
Terrence Frederick
Kedric Golston
Ricky Lumpkin
Mike Brown
Saalim Hakim
Sean McGrath
Edwin Baker
Loni Fangupo
Eddie Pleasant
Cam Johnson
Chris Hogan
Greg Jones
Greg Jones
Junior Hemingway
Tony Jerod-Eddie
Ifeanyi Momah
Russell Shepard
Damion Square
Matthew Tucker
Brad Wing
Matt Barkley
Zach Ertz
Brandon Meriweather
Joe Kruger
Bennie Logan
Jordan Poyer
Earl Wolff
Kiko Alonso
Marquise Goodwin
Chris Gragg
Dustin Hopkins
E.J. Manuel
Jon Ryan
Jonathan Meeks
Duke Williams
Robert Woods
Mike Gillislee
Jelani Jenkins
Don Jones
Dion Jordan
Dion Sims
Jamar Taylor
Steve Beauharnais
Josh Boyce
Michael Buchanan
Jamie Collins
Aaron Dobson
Duron Harmon
Logan Ryan
Tommy Bohanon
Curtis Lofton
Dee Milliner
Sheldon Richardson
Geno Smith
Marc Anthony
Arthur Brown
Matt Elam
Kyle Juszczyk
Ben Roethlisberger
Kapron Lewis-Moore
John Simon
Brandon Williams
Jayson DiManche
Giovani Bernard
Rex Burkhead
Tyler Eifert
William Hayes
Cobi Hamilton
Margus Hunt
T.J. Johnson
Sean Porter
Shawn Williams
Josh Aubrey
Jacob Schum
Sidney Rice
Erin Henderson
Justin Staples
Armonty Bryant
Leon McFadden
Barkevious Mingo
Le'Veon Bell
Justin Brown
Kevin Reddick
Jarvis Jones
Landry Jones
Shamarko Thomas
Markus Wheaton
Nick Williams
Vince Williams
Lavar Edwards
Zaviar Gooden
Justin Hunter
Tony Romo
Daimion Stafford
Khalid Wooten
Blidi Wreh-Wilson
Ryan Griffin
DeAndre Hopkins
D.J. Swearinger
Chris Jones
Brandon McManus
Sheldon Price
Justice Cunningham
Montori Hughes
Matt Flynn
Bjoern Werner
Kerwynn Williams
Chris Banjo
Johnathan Cyprien
Josh Evans
Dwayne Gratz
Jeremy Harris
Demetrius McCray
Denard Robinson
Rashard Mendenhall
Ace Sanders
C.J. Anderson
Lerentee McCray
Montee Ball
Zac Dysert
Tavarres King
Quanterus Smith
Kayvon Webster
Tramon Williams
Sylvester Williams
Mike Catapano
Sanders Commings
Knile Davis
Nico Johnson
Travis Kelce
Brian Leonhardt
DeSean Jackson
Brice Butler
D.J. Hayden
Nick Kasa
Stacy McGee
Sio Moore
Latavius Murray
Mychal Rivera
Keenan Allen
Andre Caldwell
Manti Te'o
Steve Williams
Tourek Williams
Gavin Escobar
Joseph Randle
B.W. Webb
J.J. Wilcox
Zackary Bowman
Terrance Williams
Michael Cox
Johnathan Hankins
Damontre Moore
Ryan Nassib
Cooper Taylor
David Amerson
Bacarri Rambo
Patrick Willis
Danieal Manning
Jordan Reed
Phillip Thomas
Chris Thompson
Michael Ford
Demontre Hurst
Josh Lenz
Tress Way
Jon Bostic
Lavelle Hawkins
Cornelius Washington
Marquess Wilson
Ezekiel Ansah
Corey Fuller
Brandon Hepburn
Sam Martin
Theo Riddick
Darius Slay
Anthony Spencer
Sam Barrington
Josh Boyd
Kevin Dorsey
Micah Hyde
Datone Jones
Eddie Lacy
Nate Palmer
Ahtyba Rubin
Charles Johnson
Gerald Hodges
Jeff Locke
Michael Mauti
Cordarrelle Patterson
Xavier Rhodes
Joplo Bartu
Paul Worrilow
Tarvaris Jackson
Robert Alford
Malliciah Goodman
Kemal Ishmael
Stansly Maponga
Sean Renfree
Desmond Trufant
Kenjon Barner
A.J. Klein
Star Lotulelei
Kawann Short
Jerricho Cotchery
Ryan Griffin
Austin Johnson
John Jenkins
Rufus Johnson
Kenny Stills
Kenny Vaccaro
Johnthan Banks
William Gholston
Mike Glennon
William Gay
Mike James
Steven Means
Akeem Spence
Daren Bates
Benny Cunningham
Cody Davis
Tavon Austin
Vince Young
T.J. McDonald
Brandon McGee
Alec Ogletree
Zac Stacy
Andre Ellington
Tyrann Mathieu
Kevin Minter
Alex Okafor
Stepfan Taylor
Dave Zastudil
Cornellius Carradine
Marcus Cooper
B.J. Daniels
Quinton Dial
Corey Lemonier
Vance McDonald
Nick Moody
Quinton Patton
Dwight Freeney
Eric Reid
Darren Fells
John Lotulelei
Chris Harper
Christine Michael
Ty Powell
Tharold Simon
Ray Rice
Paul Posluszny
Jared Smith
Spencer Ware
Jesse Williams
Luke Willson
Nick Williams
Jumal Rolle
Rontez Miles
Chris Pantale
Wes Horton
Ryan Spadola
Tyler Bray
Frankie Hammond
Josh Martin
Bradley McDougald
Rico Richardson
Demetrius Harris
Jahleel Addae
Marcus Cromartie
Josh Johnson
Will Compton
Skye Dawson
Joseph Fauria
Darius Eubanks
Rodney Smith
Rashaan Melvin
MarQueis Gray
Darryl Morris
Barry Cofield
Mike Purcell
Devin Taylor
Levine Toilolo
Jordan Dangerfield
Jeff Tuel
A.J. Francis
Keelan Johnson
Jordan Kovacs
Brandon Bostick
Zach Sudfeld
Kenbrell Thompkins
Joe Vellano
Brandon Copeland
Josh Cribbs
Brynden Trawick
T.J. Barnes
Marcus Burley
Abry Jones
Tobais Palmer
LaRoy Reynolds
Steven Terrell
Tom Brady
Lawrence Okoye
Kendall Gaskins
Nickell Robey-Coleman
Da'Rick Rogers
A.J. Bouye
Marlon Brown
Ja'Gared Davis
Earl Okine
Nick Novak
Justin Tuggle
George Winn
Cierre Wood
Charles James
Jaron Brown
Kenny Demens
Tony Jefferson
Terence Garvin
Adam Thielen
Steve Smith
Lowell Rose
Zach Line
Ryan Allen
Will Davis
Brandon Williams
David King
Jonas Gray
Brian Tyms
Matt Prater
Cliff Avril
Jeff Heath
Eric Rogers
Michael J. Thomas
Chase Reynolds
Jack Doyle
Spencer Lanning
Peyton Thompson
Fozzy Whittaker
Zach Miller
Gerald Rivers
Colton Schmidt
Cooper Helfet
Derrick Coleman
Casey Walker
Derek Carrier
Johnathan Joseph
Khiry Robinson
Rashad Ross
Nathan Stupar
Willie Jefferson
Isaiah Frey
Rod Sweeting
Andy Mulumba
Melvin White
Case Keenum
Chase Ford
Ben Jacobs
Jordan Gay
Brenton Bersin
Brittan Golden
Matthew McGloin
Jake Stoneburner
Jordy Nelson
Giorgio Tavecchio
Keavon Milton
Jordan Hill
Kashif Moore
Larry Donnell
Gary Barnidge
Daniel Adongo
Josh McNary
Benson Mayowa
Myles White
Wes Welker
Ray-Ray Armstrong
J Talley
Deon Lacey
Eric Martin
Josh Hill
Greg Jenkins
Matt Schaub
Ryan Robinson
James Winchester
Lance Lewis
Phillip Supernaw
Beau Allen
Reggie Bush
Blake Annen
Kadron Boone
Trey Burton
David Fluellen
Taylor Hart
Josh Huff
Aqib Talib
Jordan Matthews
Ed Reynolds
Marcus Smith
Jaylen Watkins
Matt Simms
Preston Brown
Ross Cockrell
Drew Stanton
Randell Johnson
Kenny Ladler
Sammy Watkins
Walt Aikens
Orleans Darkwa
Mike Tolbert
Terrence Fede
Matt Hazel
Anthony Johnson
Jarvis Landry
Arthur Lynch
Chris McCain
Glenn Dorsey
Garrison Smith
Jordan Tripp
Damien Williams
Malcolm Butler
Dominique Easley
Jimmy Garoppolo
Shamiel Gary
Adrian Peterson
Stephen Houston
Zach Moore
Deontae Skinner
Jemea Thomas
James White
Jace Amaro
Charles Tillman
Brandon Dixon
IK Enemkpali
Quincy Enunwa
Shaquelle Evans
Jeremiah George
Kerry Hyder
Dexter McDougle
DeMarcus Ware
Trevor Reilly
Jalen Saunders
Terrence Brooks
Jeremy Butler
Michael Campanaro
Crockett Gillmore
Thomas Davis
Tramain Jacobs
Timmy Jernigan
Jamie Meder
C.J. Mosley
Deji Olatoye
Zach Orr
Sammy Seamster
Eli Manning
Lorenzo Taliaferro
Brent Urban
Keith Wenning
Will Clarke
James Davidson
Darqueze Dennard
Marquis Flowers
Brandon Flowers
Ryan Hewitt
Jeremy Hill
AJ McCarron
Nikita Whitlock
James Wright
Ray Agnew
Ray Agnew
Joe Flacco
Isaiah Crowell
Pierre Desir
Taylor Gabriel
Justin Gilbert
Christian Kirksey
Jonathan Krause
Johnny Manziel
Jacobbi McDaniel
Robert Nelson
Philip Wheeler
Connor Shaw
Willie Snead
Terrance West
K'Waun Williams
Dri Archer
Martavis Bryant
Howard Jones
Adam Hayward
Josh Mauro
Daniel McCullers
Ryan Shazier
Stephon Tuitt
Antonio Andrews
Travis Coons
Justin Durant
DaQuan Jones
Zach Mettenberger
Bishop Sankey
Reggie Wayne
Avery Williamson
Jason Ankrah
Lonnie Ballentine
Alfred Blue
Chris Boswell
Max Bullough
Jadeveon Clowney
Anthony Denham
Courtney Roby
C.J. Fiedorowicz
Andre Hal
Louis Nix
Jeoffrey Pagan
Jay Prosch
Tom Savage
Leodis McKelvin
Marcus Williams
Zach Kerr
Dewey McDonald
Andy Studebaker
Donte Moncrief
Jonathan Newsome
Cody Parkey
Erik Swoope
Zurlon Tipton
Tony Washington
Blake Bortles
Kellen Clemens
Deandre Coleman
Aaron Colvin
Allen Hurns
Marcel Jensen
Storm Johnson
Marqise Lee
Craig Loston
Jon Condo
Allen Robinson
Chris Smith
Telvin Smith
Kenny Anunike
Shaquil Barrett
Jared Allen
Vernon Davis
Lamin Barrow
Kapri Bibbs
Isaiah Burse
Bennie Fowler
Cody Latimer
Corey Nelson
Bradley Roby
Marques Colston
Lou Young
Dee Ford
Phillip Gaines
Aaron Murray
Cairo Santos
Daniel Sorensen
De'Anthony Thomas
Charcandrick West
Albert Wilson
George Atkinson
Denico Autry
Derek Carr
T.J. Carrie
Jacoby Jones
Jonathan Dowling
Justin Ellis
Carlos Fields
Shelby Harris
Khalil Mack
Keith McGill
Jake Murphy
Seth Roberts
Scott Simonson
Jeremiah Attaochu
Ryan Carrethers
Chris Davis
Greg Ducre
Marion Grice
Javontee Herndon
Vince Wilfork
Branden Oliver
Tenny Palepoi
Jason Verrett
Ken Bishop
Davon Coleman
Anthony Hitchens
DeMarcus Lawrence
Terrance Mitchell
Tyler Patmon
Donald Penn
Dashaun Phillips
Keith Smith
Devin Street
Odell Beckham
Nat Berhe
Josh McCown
Jay Bromley
Xavier Grimble
Bennett Jackson
Devon Kennard
Kelcy Quarles
Andre Williams
Kerry Wynn
Jonathan Babineaux
Bashaud Breeland
Akeem Davis
Ryan Grant
Zach Hocker
Trent Murphy
Wesley Woodyard
Silas Redd
Lache Seastrunk
Robert Thomas
Ka'Deem Carey
Brandon Dunn
David Fales
Ego Ferguson
Kyle Fuller
Daryl Smith
Christian Jones
DeDe Lattimore
Pat O'Donnell
Senorise Perry
Will Sutton
Brock Vereen
Jerome Couplin
Eric Ebron
T.J. Jones
Nevin Lawson
Caraun Reid
Mohammed Seisay
Jordan Thompson
Kyle Van Noy
Larry Webster
Jared Abbrederis
Davante Adams
Carl Bradford
Ha Ha Clinton-Dix
Demetri Goodson
Adrian Hubbard
Osi Umenyiora
Jeff Janis
Mike Pennel
Justin Perillo
Richard Rodgers
Joe Thomas
Khyri Thornton
Jason Snelling
Anthony Barr
Teddy Bridgewater
Rakim Cox
Scott Crichton
Antone Exum
Jerick McKinnon
Jabari Price
Shamar Stephen
Brandon Watts
Ricardo Allen
Devonta Freeman
Donte Whitner
Ra'Shede Hageman
Freddie Martino
Roosevelt Nix
Yawin Smallwood
Jerome Smith
Dezmen Southward
Marquis Spruill
Jonathan Stewart
Kelvin Benjamin
Bene' Benwikere
Tre Boston
Corey Brown
Tyler Gaffney
Mario Williams
Adarius Taylor
Darrin Reaves
Marcus Ball
Brandon Coleman
Brandin Cooks
Brian Dixon
Kasim Edebali
LaMarr Woodley
DeMeco Ryans
Khairi Fortt
Je'Ron Hamm
Nic Jacobs
Stanley Jean-Baptiste
Seantavius Jones
Ronald Powell
Vinnie Sunseri
Brent Celek
Pierre Warren
Cameron Brate
Mike Evans
Robert Herron
Patrick Murray
Josh Morgan
Solomon Patton
Austin Seferian-Jenkins
Charles Sims
Maurice Alexander
Alex Bayer
Christian Bryant
Aaron Donald
Garrett Gilbert
Larry Fitzgerald
Lamarcus Joyner
Tre Mason
Marcus Roberson
Trey Watts
Ethan Westbrooks
John Brown
Deone Bucannon
Glenn Carson
Chandler Catanzaro
Bruce Gaston
Kareem Martin
Troy Niklas
L.P. LaDouceur
Ed Stinson
Logan Thomas
Corey Washington
Kenneth Acker
Asante Cleveland
Bruce Ellington
Carlos Hyde
Dontae Johnson
Aaron Lynch
Antwaan Randle El
L.J. McCray
Keith Reaser
Shayne Skov
Jimmie Ward
Rashaun Allen
Dion Bailey
Alan Ball
Brock Coyle
Jackson Jeffcoat
Cassius Marsh
Kevin Norwood
Kevin Pierre-Louis
Eric Pinkins
Paul Richardson
Fred Jackson
Kiero Small
Fitzgerald Toussaint
James Wilder
James Morris
Adrian Phillips
Cordarro Law
Phil Dawson
Dontrelle Inman
Chris Matthews
Kevin Smith
Kevin Smith
Terrance Parks
Glenn Winston
Jason Witten
Robert Meachem
Chandler Fenner
Al Louis-Jean
T.J. Fatinikun
Josh Harris
Jerome Cunningham
Jameis Winston
Marcus Mariota
Dante Fowler
Amari Cooper
Mike Devito
Leonard Williams
Kevin White
Vic Beasley
Todd Gurley
Trae Waynes
Danny Shelton
DeVante Parker
Frank Gore
Melvin Gordon
Kevin Johnson
Arik Armstead
Marcus Peters
Nelson Agholor
Bud Dupree
Shane Ray
Matt Moore
Shaq Thompson
Breshad Perriman
Byron Jones
Phillip Dorsett
Damarious Randall
Stephone Anthony
Malcom Brown
Landon Collins
Mario Edwards
T.J. Yeldon
Devin Smith
Preston Smith
Eddie Goldman
Dorial Green-Beckham
Devin Funchess
Jalen Collins
Benardrick McKinney
Hau'oli Kikaha
Terence Newman
Eric Kendricks
Jaquiski Tartt
Eric Rowe
Denzel Perryman
Ronald Darby
Nate Orchard
Jordan Phillips
Ameer Abdullah
Domata Peko
Maxx Williams
Senquez Golson
Markus Golden
Randy Gregory
Quinten Rollins
Frank Clark
Jordan Richards
Charles Godfrey
D'Joun Smith
Clive Walford
Tyler Lockett
Jaelen Strong
Tevin Coleman
Owamagbe Odighizuwa
Dashon Goldson
Garrett Grayson
Chris Conley
Duke Johnson
P.J. Williams
Eli Harold
Alex Carter
Lorenzo Mauldin
Craig Mager
Jordan Hicks
Cullen Jenkins
Tyler Kroft
David Johnson
Sammie Coates
Danielle Hunter
Sean Mannion
Carl Davis
Jeff Heuerman
Henry Anderson
Ty Montgomery
Matt Ryan
Calvin Johnson
Matt Jones
Xavier Cooper
Geneo Grissom
Steven Nelson
Paul Dawson
Angelo Blackson
Trey Flowers
Bryce Petty
James Sample
Spencer Larsen
Jamison Crowder
Jeremy Langford
Justin Hardy
Jalston Fowler
Clayton Geathers
Gabe Wright
Brent Grimes
Ibraheim Campbell
Rodney Gunter
Blake Bell
Ramik Wilson
Josh Shaw
Doran Grant
Za'Darius Smith
Vince Mayle
Kwon Alexander
Ben Obomanu
Javorius Allen
Mike Davis
Damien Wilson
Jake Ryan
DeAndre Smelter
Tray Walker
David Cobb
Rashad Greene
Ben Heeney
Martrell Spaight
Adrian Amos
MyCole Pruitt
Mykkele Thompson
Bobby McCain
Stefon Diggs
Thomas Howard
Brett Hundley
Jay Ajayi
Cedric Thompson
David Parry
Kyle Emanuel
Tyeler Davison
Karlos Williams
Tony Lippett
Darren Sproles
C.J. Uzomah
Shaquille Riddick
J.J. Nelson
Jesse James
Neiron Ball
Lorenzo Doss
Bradley Pinion
Harry Douglas
Damian Swann
Michael Burton
David Mayo
Tye Smith
Nick Boyle
D.J. Alexander
James O'Shaughnessy
Cameron Artis-Payne
Keith Mumphery
Deiontrez Mount
Luke McCown
Max Valles
Michael Bennett
Kaelin Clay
Geremy Davis
Tony Steward
Chad Greenway
Charles Gaines
JaCorey Shepherd
Darius Philon
Nick O'Leary
Malcolm Johnson
Randall Evans
Derron Smith
Randall Telfer
Jerome Felton
Leterrius Walton
Quandre Diggs
A.J. Derby
Darius Kilgo
Darren Waller
Josh Robinson
Aaron Ripkowski
Amarlo Herrera

In [ ]:
astro_df = birthloc_df.join(pd.json_normalize(birthloc_df['astro']))
astro_df.to_csv('/content/drive/My Drive/ff/astro_df.csv')

In [ ]:
birthloc_df[birthloc_df['astro'].isna()]

KeyError: 'astro'

In [ ]:
astro_df

,full_name,number,team,position,birthdate,active,espn_id,sleeper_id,birthplace,latitude,...,twelfth_house.quality,twelfth_house.element,twelfth_house.sign,twelfth_house.sign_num,twelfth_house.position,twelfth_house.abs_pos,twelfth_house.emoji,twelfth_house.point_type,twelfth_house.house,twelfth_house.retrograde
1,GJ Kinne,2,PHI,QB,1988-12-01,False,15299,1,"Mesquite, TX",32.766610,...,Mutable,Water,Pis,11.0,0.302447,330.302447,♓️,House,None,None
3,David Harris,45,FA,LB,1984-01-21,False,10491,3,"Grand Rapids, MI",42.963242,...,Cardinal,Water,Can,3.0,26.616386,116.616386,♋️,House,None,None
4,Roddy White,84,FA,WR,1981-11-02,False,8442,4,"James Island, SC",32.734346,...,Cardinal,Earth,Cap,9.0,3.384406,273.384406,♑️,House,None,None
5,Dallas Clark,87,FA,TE,1979-06-12,False,4482,5,"Livermore, IA",42.868324,...,Fixed,Earth,Tau,1.0,11.341688,41.341688,♉️,House,None,None
6,Brandon Mebane,92,FA,DT,1985-01-15,True,10529,6,"Los Angeles, CA",34.053691,...,Mutable,Air,Gem,2.0,29.120164,89.120164,♊️,House,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12357,David Martin-Robinson,88,TEN,TE,1999-12-26,True,4360978,12357,"Landisville, PA",40.095120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12385,Jude McAtamney,99,NYG,PK,2000-05-09,True,5092436,12385,"Derry, Ireland",54.997868,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12402,Ramon Jefferson,45,TBB,RB,2000-01-10,True,4250013,12402,"Bronx, NY",40.846651,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12420,Gable Steveson,61,BUF,DT,2000-05-31,True,5214652,12420,"Apple Valley, MN",44.731909,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12421,David Wallis,30,NEP,WR,2001-08-08,True,5215032,12421,"Cedar Point, NC",34.687630,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
astro_df.drop('astro', axis=1, inplace=True)

In [ ]:
astro_df.to_csv('/content/drive/My Drive/ff/astro_df.csv')

In [ ]:
birthloc_df.to_csv('/content/drive/My Drive/ff/birthloc_final_df.csv')

In [ ]:
import pandas as pd
birthloc_df= pd.read_csv('/content/drive/My Drive/ff/birthloc_final_df.csv', index_col=0)
birthloc_df['astro'] = birthloc_df['astro'].map(ast.literal_eval)
print(type(birthloc_df.iloc[0]['astro']))

<class 'dict'>

In [ ]:
print(type(birthloc_df.iloc[0]['astro']))
test_df = birthloc_df
print(type(test_df.iloc[0]['astro']))
pd.json_normalize(test_df.iloc[0]['astro'])

<class 'str'>
<class 'dict'>

In [ ]:
print(type(birthloc_df.iloc[0]['astro']))
test_df = birthloc_df
print(type(test_df.iloc[0]['astro']))
pd.json_normalize(test_df.iloc[0]['astro'])

<class 'dict'>
<class 'dict'>

,chart,sun.name,sun.quality,sun.element,sun.sign,sun.sign_num,sun.position,sun.abs_pos,sun.emoji,sun.point_type,...,twelfth_house.quality,twelfth_house.element,twelfth_house.sign,twelfth_house.sign_num,twelfth_house.position,twelfth_house.abs_pos,twelfth_house.emoji,twelfth_house.point_type,twelfth_house.house,twelfth_house.retrograde
0,b'PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nVVRG...,Sun,Mutable,Fire,Sag,8,9.77365,249.77365,♐️,Planet,...,Cardinal,Earth,Cap,9,22.587815,292.587815,♑️,House,None,None

In [ ]:
a = pd.json_normalize(test_df['astro'])
bi = list(birthloc_df.index)
a.index = bi
a

,chart,sun.name,sun.quality,sun.element,sun.sign,sun.sign_num,sun.position,sun.abs_pos,sun.emoji,sun.point_type,...,twelfth_house.quality,twelfth_house.element,twelfth_house.sign,twelfth_house.sign_num,twelfth_house.position,twelfth_house.abs_pos,twelfth_house.emoji,twelfth_house.point_type,twelfth_house.house,twelfth_house.retrograde
1,b'PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nVVRG...,Sun,Mutable,Fire,Sag,8,9.773650,249.773650,♐️,Planet,...,Cardinal,Earth,Cap,9,22.587815,292.587815,♑️,House,None,None
10,b'PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nVVRG...,Sun,Cardinal,Earth,Cap,9,11.237749,281.237749,♑️,Planet,...,Mutable,Water,Pis,11,0.302447,330.302447,♓️,House,None,None
100,b'PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nVVRG...,Sun,Cardinal,Air,Lib,6,14.507344,194.507344,♎️,Planet,...,Fixed,Water,Sco,7,15.680251,225.680251,♏️,House,None,None
1000,b'PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nVVRG...,Sun,Mutable,Air,Gem,2,13.732994,73.732994,♊️,Planet,...,Cardinal,Water,Can,3,26.616386,116.616386,♋️,House,None,None
1001,b'PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nVVRG...,Sun,Fixed,Water,Sco,7,17.603319,227.603319,♏️,Planet,...,Cardinal,Earth,Cap,9,3.384406,273.384406,♑️,House,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,b'PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nVVRG...,Sun,Cardinal,Fire,Ari,0,10.331287,10.331287,♈️,Planet,...,Mutable,Air,Gem,2,22.057467,82.057467,♊️,House,None,None
997,b'PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nVVRG...,Sun,Cardinal,Water,Can,3,13.714875,103.714875,♋️,Planet,...,Mutable,Earth,Vir,5,3.047502,153.047502,♍️,House,None,None
998,b'PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nVVRG...,Sun,Fixed,Fire,Leo,4,0.804601,120.804601,♌️,Planet,...,Mutable,Earth,Vir,5,17.849025,167.849025,♍️,House,None,None
999,b'PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nVVRG...,Sun,Fixed,Water,Sco,7,9.734703,219.734703,♏️,Planet,...,Mutable,Fire,Sag,8,28.525064,268.525064,♐️,House,None,None
9997,b'PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nVVRG...,Sun,Mutable,Earth,Vir,5,19.209646,169.209646,♍️,Planet,...,Cardinal,Air,Lib,6,29.175462,209.175462,♎️,House,None,None

In [ ]:
test_df = test_df.join(a)
test_df.drop('astro', axis='columns')
test_df

,full_name,number,team,position,birthdate,active,espn_id,sleeper_id,birthplace,latitude,...,twelfth_house.quality,twelfth_house.element,twelfth_house.sign,twelfth_house.sign_num,twelfth_house.position,twelfth_house.abs_pos,twelfth_house.emoji,twelfth_house.point_type,twelfth_house.house,twelfth_house.retrograde
1,GJ Kinne,2,PHI,QB,1988-12-01,False,15299,1,"Mesquite, TX",32.766610,...,Cardinal,Earth,Cap,9,22.587815,292.587815,♑️,House,None,None
3,David Harris,45,FA,LB,1984-01-21,False,10491,3,"Grand Rapids, MI",42.963242,...,Mutable,Water,Pis,11,14.572143,344.572143,♓️,House,None,None
4,Roddy White,84,FA,WR,1981-11-02,False,8442,4,"James Island, SC",32.734346,...,Mutable,Fire,Sag,8,26.461439,266.461439,♐️,House,None,None
5,Dallas Clark,87,FA,TE,1979-06-12,False,4482,5,"Livermore, IA",42.868324,...,Fixed,Fire,Leo,4,10.258602,130.258602,♌️,House,None,None
6,Brandon Mebane,92,FA,DT,1985-01-15,True,10529,6,"Los Angeles, CA",34.053691,...,Mutable,Water,Pis,11,25.891687,355.891687,♓️,House,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12357,David Martin-Robinson,88,TEN,TE,1999-12-26,True,4360978,12357,"Landisville, PA",40.095120,...,Fixed,Air,Aqu,10,23.014166,323.014166,♒️,House,None,None
12385,Jude McAtamney,99,NYG,PK,2000-05-09,True,5092436,12385,"Derry, Ireland",54.997868,...,Cardinal,Water,Can,3,17.634914,107.634914,♋️,House,None,None
12402,Ramon Jefferson,45,TBB,RB,2000-01-10,True,4250013,12402,"Bronx, NY",40.846651,...,Mutable,Water,Pis,11,16.491191,346.491191,♓️,House,None,None
12420,Gable Steveson,61,BUF,DT,2000-05-31,True,5214652,12420,"Apple Valley, MN",44.731909,...,Fixed,Fire,Leo,4,2.725535,122.725535,♌️,House,None,None
12421,David Wallis,30,NEP,WR,2001-08-08,True,5215032,12421,"Cedar Point, NC",34.687630,...,Cardinal,Air,Lib,6,0.137548,180.137548,♎️,House,None,None

In [ ]:
test_df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 4789 entries, 1 to 12421
Data columns (total 302 columns):
 #    Column                     Non-Null Count  Dtype
---   ------                     --------------  -----
 0    full_name                  4789 non-null   object
 1    number                     4789 non-null   int64
 2    team                       4789 non-null   object
 3    position                   4789 non-null   object
 4    birthdate                  4789 non-null   object
 5    active                     4789 non-null   bool
 6    espn_id                    4789 non-null   int64
 7    sleeper_id                 4789 non-null   int64
 8    birthplace                 4789 non-null   object
 9    latitude                   4789 non-null   float64
 10   longitude                  4789 non-null   float64
 11   birthtime                  4789 non-null   object
 12   birthtime_true             4789 non-null   bool
 13   timezone                   4789 non-null   object
 14   astro                      4789 non-null   object
 15   chart                      4789 non-null   object
 16   sun.name                   4789 non-null   object
 17   sun.quality                4789 non-null   object
 18   sun.element                4789 non-null   object
 19   sun.sign                   4789 non-null   object
 20   sun.sign_num               4789 non-null   int64
 21   sun.position               4789 non-null   float64
 22   sun.abs_pos                4789 non-null   float64
 23   sun.emoji                  4789 non-null   object
 24   sun.point_type             4789 non-null   object
 25   sun.house                  4789 non-null   object
 26   sun.retrograde             4789 non-null   bool
 27   moon.name                  4789 non-null   object
 28   moon.quality               4789 non-null   object
 29   moon.element               4789 non-null   object
 30   moon.sign                  4789 non-null   object
 31   moon.sign_num              4789 non-null   int64
 32   moon.position              4789 non-null   float64
 33   moon.abs_pos               4789 non-null   float64
 34   moon.emoji                 4789 non-null   object
 35   moon.point_type            4789 non-null   object
 36   moon.house                 4789 non-null   object
 37   moon.retrograde            4789 non-null   bool
 38   mercury.name               4789 non-null   object
 39   mercury.quality            4789 non-null   object
 40   mercury.element            4789 non-null   object
 41   mercury.sign               4789 non-null   object
 42   mercury.sign_num           4789 non-null   int64
 43   mercury.position           4789 non-null   float64
 44   mercury.abs_pos            4789 non-null   float64
 45   mercury.emoji              4789 non-null   object
 46   mercury.point_type         4789 non-null   object
 47   mercury.house              4789 non-null   object
 48   mercury.retrograde         4789 non-null   bool
 49   venus.name                 4789 non-null   object
 50   venus.quality              4789 non-null   object
 51   venus.element              4789 non-null   object
 52   venus.sign                 4789 non-null   object
 53   venus.sign_num             4789 non-null   int64
 54   venus.position             4789 non-null   float64
 55   venus.abs_pos              4789 non-null   float64
 56   venus.emoji                4789 non-null   object
 57   venus.point_type           4789 non-null   object
 58   venus.house                4789 non-null   object
 59   venus.retrograde           4789 non-null   bool
 60   mars.name                  4789 non-null   object
 61   mars.quality               4789 non-null   object
 62   mars.element               4789 non-null   object
 63   mars.sign                  4789 non-null   object
 64   mars.sign_num              4789 non-null   int64
 65   mars.position              4789 non-null   float64
 66   mars.abs_pos               4789 non-null   float64
 67   mars.emoji                 4789 non-null   object
 68   mars.point_type            4789 non-null   object
 69   mars.house                 4789 non-null   object
 70   mars.retrograde            4789 non-null   bool
 71   jupiter.name               4789 non-null   object
 72   jupiter.quality            4789 non-null   object
 73   jupiter.element            4789 non-null   object
 74   jupiter.sign               4789 non-null   object
 75   jupiter.sign_num           4789 non-null   int64
 76   jupiter.position           4789 non-null   float64
 77   jupiter.abs_pos            4789 non-null   float64
 78   jupiter.emoji              4789 non-null   object
 79   jupiter.point_type         4789 non-null   object
 80   jupiter.house              4789 non-null   object
 81   jupiter.retrograde         4789 non-null   bool
 82   saturn.name                4789 non-null   object
 83   saturn.quality             4789 non-null   object
 84   saturn.element             4789 non-null   object
 85   saturn.sign                4789 non-null   object
 86   saturn.sign_num            4789 non-null   int64
 87   saturn.position            4789 non-null   float64
 88   saturn.abs_pos             4789 non-null   float64
 89   saturn.emoji               4789 non-null   object
 90   saturn.point_type          4789 non-null   object
 91   saturn.house               4789 non-null   object
 92   saturn.retrograde          4789 non-null   bool
 93   uranus.name                4789 non-null   object
 94   uranus.quality             4789 non-null   object
 95   uranus.element             4789 non-null   object
 96   uranus.sign                4789 non-null   object
 97   uranus.sign_num            4789 non-null   int64
 98   uranus.position            4789 non-null   float64
 99   uranus.abs_pos             4789 non-null   float64
 100  uranus.emoji               4789 non-null   object
 101  uranus.point_type          4789 non-null   object
 102  uranus.house               4789 non-null   object
 103  uranus.retrograde          4789 non-null   bool
 104  neptune.name               4789 non-null   object
 105  neptune.quality            4789 non-null   object
 106  neptune.element            4789 non-null   object
 107  neptune.sign               4789 non-null   object
 108  neptune.sign_num           4789 non-null   int64
 109  neptune.position           4789 non-null   float64
 110  neptune.abs_pos            4789 non-null   float64
 111  neptune.emoji              4789 non-null   object
 112  neptune.point_type         4789 non-null   object
 113  neptune.house              4789 non-null   object
 114  neptune.retrograde         4789 non-null   bool
 115  pluto.name                 4789 non-null   object
 116  pluto.quality              4789 non-null   object
 117  pluto.element              4789 non-null   object
 118  pluto.sign                 4789 non-null   object
 119  pluto.sign_num             4789 non-null   int64
 120  pluto.position             4789 non-null   float64
 121  pluto.abs_pos              4789 non-null   float64
 122  pluto.emoji                4789 non-null   object
 123  pluto.point_type           4789 non-null   object
 124  pluto.house                4789 non-null   object
 125  pluto.retrograde           4789 non-null   bool
 126  true_node.name             4789 non-null   object
 127  true_node.quality          4789 non-null   object
 128  true_node.element          4789 non-null   object
 129  true_node.sign             4789 non-null   object
 130  true_node.sign_num         4789 non-null   int64
 131  true_node.position         4789 non-null   float64
 132  true_node.abs_pos          4789 non-null   float64
 133  true_node.emoji            4789 non-null   object
 134  true_node.point_type       4789 non-null   object
 135  true_node.house            4789 non-null   object
 136  true_node.retrograde       4789 non-null   bool
 137  mean_node.name             4789 non-null   object
 138  mean_node.quality          4789 non-null   object
 139  mean_node.element          4789 non-null   object
 140  mean_node.sign             4789 non-null   object
 141  mean_node.sign_num         4789 non-null   int64
 142  mean_node.position         4789 non-null   float64
 143  mean_node.abs_pos          4789 non-null   float64
 144  mean_node.emoji            4789 non-null   object
 145  mean_node.point_type       4789 non-null   object
 146  mean_node.house            4789 non-null   object
 147  mean_node.retrograde       4789 non-null   bool
 148  chiron.name                4789 non-null   object
 149  chiron.quality             4789 non-null   object
 150  chiron.element             4789 non-null   object
 151  chiron.sign                4789 non-null   object
 152  chiron.sign_num            4789 non-null   int64
 153  chiron.position            4789 non-null   float64
 154  chiron.abs_pos             4789 non-null   float64
 155  chiron.emoji               4789 non-null   object
 156  chiron.point_type          4789 non-null   object
 157  chiron.house               4789 non-null   object
 158  chiron.retrograde          4789 non-null   bool
 159  mean_lilith.name           4789 non-null   object
 160  mean_lilith.quality        4789 non-null   object
 161  mean_lilith.element        4789 non-null   object
 162  mean_lilith.sign           4789 non-null   object
 163  mean_lilith.sign_num       4789 non-null   int64
 164  mean_lilith.position       4789 non-null   float64
 165  mean_lilith.abs_pos        4789 non-null   float64
 166  mean_lilith.emoji          4789 non-null   object
 167  mean_lilith.point_type     4789 non-null   object
 168  mean_lilith.house          4789 non-null   object
 169  mean_lilith.retrograde     4789 non-null   bool
 170  first_house.name           4789 non-null   object
 171  first_house.quality        4789 non-null   object
 172  first_house.element        4789 non-null   object
 173  first_house.sign           4789 non-null   object
 174  first_house.sign_num       4789 non-null   int64
 175  first_house.position       4789 non-null   float64
 176  first_house.abs_pos        4789 non-null   float64
 177  first_house.emoji          4789 non-null   object
 178  first_house.point_type     4789 non-null   object
 179  first_house.house          0 non-null      object
 180  first_house.retrograde     0 non-null      object
 181  second_house.name          4789 non-null   object
 182  second_house.quality       4789 non-null   object
 183  second_house.element       4789 non-null   object
 184  second_house.sign          4789 non-null   object
 185  second_house.sign_num      4789 non-null   int64
 186  second_house.position      4789 non-null   float64
 187  second_house.abs_pos       4789 non-null   float64
 188  second_house.emoji         4789 non-null   object
 189  second_house.point_type    4789 non-null   object
 190  second_house.house         0 non-null      object
 191  second_house.retrograde    0 non-null      object
 192  third_house.name           4789 non-null   object
 193  third_house.quality        4789 non-null   object
 194  third_house.element        4789 non-null   object
 195  third_house.sign           4789 non-null   object
 196  third_house.sign_num       4789 non-null   int64
 197  third_house.position       4789 non-null   float64
 198  third_house.abs_pos        4789 non-null   float64
 199  third_house.emoji          4789 non-null   object
 200  third_house.point_type     4789 non-null   object
 201  third_house.house          0 non-null      object
 202  third_house.retrograde     0 non-null      object
 203  fourth_house.name          4789 non-null   object
 204  fourth_house.quality       4789 non-null   object
 205  fourth_house.element       4789 non-null   object
 206  fourth_house.sign          4789 non-null   object
 207  fourth_house.sign_num      4789 non-null   int64
 208  fourth_house.position      4789 non-null   float64
 209  fourth_house.abs_pos       4789 non-null   float64
 210  fourth_house.emoji         4789 non-null   object
 211  fourth_house.point_type    4789 non-null   object
 212  fourth_house.house         0 non-null      object
 213  fourth_house.retrograde    0 non-null      object
 214  fifth_house.name           4789 non-null   object
 215  fifth_house.quality        4789 non-null   object
 216  fifth_house.element        4789 non-null   object
 217  fifth_house.sign           4789 non-null   object
 218  fifth_house.sign_num       4789 non-null   int64
 219  fifth_house.position       4789 non-null   float64
 220  fifth_house.abs_pos        4789 non-null   float64
 221  fifth_house.emoji          4789 non-null   object
 222  fifth_house.point_type     4789 non-null   object
 223  fifth_house.house          0 non-null      object
 224  fifth_house.retrograde     0 non-null      object
 225  sixth_house.name           4789 non-null   object
 226  sixth_house.quality        4789 non-null   object
 227  sixth_house.element        4789 non-null   object
 228  sixth_house.sign           4789 non-null   object
 229  sixth_house.sign_num       4789 non-null   int64
 230  sixth_house.position       4789 non-null   float64
 231  sixth_house.abs_pos        4789 non-null   float64
 232  sixth_house.emoji          4789 non-null   object
 233  sixth_house.point_type     4789 non-null   object
 234  sixth_house.house          0 non-null      object
 235  sixth_house.retrograde     0 non-null      object
 236  seventh_house.name         4789 non-null   object
 237  seventh_house.quality      4789 non-null   object
 238  seventh_house.element      4789 non-null   object
 239  seventh_house.sign         4789 non-null   object
 240  seventh_house.sign_num     4789 non-null   int64
 241  seventh_house.position     4789 non-null   float64
 242  seventh_house.abs_pos      4789 non-null   float64
 243  seventh_house.emoji        4789 non-null   object
 244  seventh_house.point_type   4789 non-null   object
 245  seventh_house.house        0 non-null      object
 246  seventh_house.retrograde   0 non-null      object
 247  eighth_house.name          4789 non-null   object
 248  eighth_house.quality       4789 non-null   object
 249  eighth_house.element       4789 non-null   object
 250  eighth_house.sign          4789 non-null   object
 251  eighth_house.sign_num      4789 non-null   int64
 252  eighth_house.position      4789 non-null   float64
 253  eighth_house.abs_pos       4789 non-null   float64
 254  eighth_house.emoji         4789 non-null   object
 255  eighth_house.point_type    4789 non-null   object
 256  eighth_house.house         0 non-null      object
 257  eighth_house.retrograde    0 non-null      object
 258  ninth_house.name           4789 non-null   object
 259  ninth_house.quality        4789 non-null   object
 260  ninth_house.element        4789 non-null   object
 261  ninth_house.sign           4789 non-null   object
 262  ninth_house.sign_num       4789 non-null   int64
 263  ninth_house.position       4789 non-null   float64
 264  ninth_house.abs_pos        4789 non-null   float64
 265  ninth_house.emoji          4789 non-null   object
 266  ninth_house.point_type     4789 non-null   object
 267  ninth_house.house          0 non-null      object
 268  ninth_house.retrograde     0 non-null      object
 269  tenth_house.name           4789 non-null   object
 270  tenth_house.quality        4789 non-null   object
 271  tenth_house.element        4789 non-null   object
 272  tenth_house.sign           4789 non-null   object
 273  tenth_house.sign_num       4789 non-null   int64
 274  tenth_house.position       4789 non-null   float64
 275  tenth_house.abs_pos        4789 non-null   float64
 276  tenth_house.emoji          4789 non-null   object
 277  tenth_house.point_type     4789 non-null   object
 278  tenth_house.house          0 non-null      object
 279  tenth_house.retrograde     0 non-null      object
 280  eleventh_house.name        4789 non-null   object
 281  eleventh_house.quality     4789 non-null   object
 282  eleventh_house.element     4789 non-null   object
 283  eleventh_house.sign        4789 non-null   object
 284  eleventh_house.sign_num    4789 non-null   int64
 285  eleventh_house.position    4789 non-null   float64
 286  eleventh_house.abs_pos     4789 non-null   float64
 287  eleventh_house.emoji       4789 non-null   object
 288  eleventh_house.point_type  4789 non-null   object
 289  eleventh_house.house       0 non-null      object
 290  eleventh_house.retrograde  0 non-null      object
 291  twelfth_house.name         4789 non-null   object
 292  twelfth_house.quality      4789 non-null   object
 293  twelfth_house.element      4789 non-null   object
 294  twelfth_house.sign         4789 non-null   object
 295  twelfth_house.sign_num     4789 non-null   int64
 296  twelfth_house.position     4789 non-null   float64
 297  twelfth_house.abs_pos      4789 non-null   float64
 298  twelfth_house.emoji        4789 non-null   object
 299  twelfth_house.point_type   4789 non-null   object
 300  twelfth_house.house        0 non-null      object
 301  twelfth_house.retrograde   0 non-null      object
dtypes: bool(16), float64(54), int64(29), object(203)
memory usage: 10.6+ MB

In [ ]:
#test_df.to_csv('/content/drive/My Drive/ff/astro_df.csv')
astro_df = pd.read_csv('/content/drive/My Drive/ff/astro_df.csv', index_col=0)
astro_df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 4789 entries, 1 to 12421
Data columns (total 302 columns):
 #    Column                     Non-Null Count  Dtype
---   ------                     --------------  -----
 0    full_name                  4789 non-null   object
 1    number                     4789 non-null   int64
 2    team                       4789 non-null   object
 3    position                   4789 non-null   object
 4    birthdate                  4789 non-null   object
 5    active                     4789 non-null   bool
 6    espn_id                    4789 non-null   int64
 7    sleeper_id                 4789 non-null   int64
 8    birthplace                 4789 non-null   object
 9    latitude                   4789 non-null   float64
 10   longitude                  4789 non-null   float64
 11   birthtime                  4789 non-null   object
 12   birthtime_true             4789 non-null   bool
 13   timezone                   4789 non-null   object
 14   astro                      4789 non-null   object
 15   chart                      4789 non-null   object
 16   sun.name                   4789 non-null   object
 17   sun.quality                4789 non-null   object
 18   sun.element                4789 non-null   object
 19   sun.sign                   4789 non-null   object
 20   sun.sign_num               4789 non-null   int64
 21   sun.position               4789 non-null   float64
 22   sun.abs_pos                4789 non-null   float64
 23   sun.emoji                  4789 non-null   object
 24   sun.point_type             4789 non-null   object
 25   sun.house                  4789 non-null   object
 26   sun.retrograde             4789 non-null   bool
 27   moon.name                  4789 non-null   object
 28   moon.quality               4789 non-null   object
 29   moon.element               4789 non-null   object
 30   moon.sign                  4789 non-null   object
 31   moon.sign_num              4789 non-null   int64
 32   moon.position              4789 non-null   float64
 33   moon.abs_pos               4789 non-null   float64
 34   moon.emoji                 4789 non-null   object
 35   moon.point_type            4789 non-null   object
 36   moon.house                 4789 non-null   object
 37   moon.retrograde            4789 non-null   bool
 38   mercury.name               4789 non-null   object
 39   mercury.quality            4789 non-null   object
 40   mercury.element            4789 non-null   object
 41   mercury.sign               4789 non-null   object
 42   mercury.sign_num           4789 non-null   int64
 43   mercury.position           4789 non-null   float64
 44   mercury.abs_pos            4789 non-null   float64
 45   mercury.emoji              4789 non-null   object
 46   mercury.point_type         4789 non-null   object
 47   mercury.house              4789 non-null   object
 48   mercury.retrograde         4789 non-null   bool
 49   venus.name                 4789 non-null   object
 50   venus.quality              4789 non-null   object
 51   venus.element              4789 non-null   object
 52   venus.sign                 4789 non-null   object
 53   venus.sign_num             4789 non-null   int64
 54   venus.position             4789 non-null   float64
 55   venus.abs_pos              4789 non-null   float64
 56   venus.emoji                4789 non-null   object
 57   venus.point_type           4789 non-null   object
 58   venus.house                4789 non-null   object
 59   venus.retrograde           4789 non-null   bool
 60   mars.name                  4789 non-null   object
 61   mars.quality               4789 non-null   object
 62   mars.element               4789 non-null   object
 63   mars.sign                  4789 non-null   object
 64   mars.sign_num              4789 non-null   int64
 65   mars.position              4789 non-null   float64
 66   mars.abs_pos               4789 non-null   float64
 67   mars.emoji                 4789 non-null   object
 68   mars.point_type            4789 non-null   object
 69   mars.house                 4789 non-null   object
 70   mars.retrograde            4789 non-null   bool
 71   jupiter.name               4789 non-null   object
 72   jupiter.quality            4789 non-null   object
 73   jupiter.element            4789 non-null   object
 74   jupiter.sign               4789 non-null   object
 75   jupiter.sign_num           4789 non-null   int64
 76   jupiter.position           4789 non-null   float64
 77   jupiter.abs_pos            4789 non-null   float64
 78   jupiter.emoji              4789 non-null   object
 79   jupiter.point_type         4789 non-null   object
 80   jupiter.house              4789 non-null   object
 81   jupiter.retrograde         4789 non-null   bool
 82   saturn.name                4789 non-null   object
 83   saturn.quality             4789 non-null   object
 84   saturn.element             4789 non-null   object
 85   saturn.sign                4789 non-null   object
 86   saturn.sign_num            4789 non-null   int64
 87   saturn.position            4789 non-null   float64
 88   saturn.abs_pos             4789 non-null   float64
 89   saturn.emoji               4789 non-null   object
 90   saturn.point_type          4789 non-null   object
 91   saturn.house               4789 non-null   object
 92   saturn.retrograde          4789 non-null   bool
 93   uranus.name                4789 non-null   object
 94   uranus.quality             4789 non-null   object
 95   uranus.element             4789 non-null   object
 96   uranus.sign                4789 non-null   object
 97   uranus.sign_num            4789 non-null   int64
 98   uranus.position            4789 non-null   float64
 99   uranus.abs_pos             4789 non-null   float64
 100  uranus.emoji               4789 non-null   object
 101  uranus.point_type          4789 non-null   object
 102  uranus.house               4789 non-null   object
 103  uranus.retrograde          4789 non-null   bool
 104  neptune.name               4789 non-null   object
 105  neptune.quality            4789 non-null   object
 106  neptune.element            4789 non-null   object
 107  neptune.sign               4789 non-null   object
 108  neptune.sign_num           4789 non-null   int64
 109  neptune.position           4789 non-null   float64
 110  neptune.abs_pos            4789 non-null   float64
 111  neptune.emoji              4789 non-null   object
 112  neptune.point_type         4789 non-null   object
 113  neptune.house              4789 non-null   object
 114  neptune.retrograde         4789 non-null   bool
 115  pluto.name                 4789 non-null   object
 116  pluto.quality              4789 non-null   object
 117  pluto.element              4789 non-null   object
 118  pluto.sign                 4789 non-null   object
 119  pluto.sign_num             4789 non-null   int64
 120  pluto.position             4789 non-null   float64
 121  pluto.abs_pos              4789 non-null   float64
 122  pluto.emoji                4789 non-null   object
 123  pluto.point_type           4789 non-null   object
 124  pluto.house                4789 non-null   object
 125  pluto.retrograde           4789 non-null   bool
 126  true_node.name             4789 non-null   object
 127  true_node.quality          4789 non-null   object
 128  true_node.element          4789 non-null   object
 129  true_node.sign             4789 non-null   object
 130  true_node.sign_num         4789 non-null   int64
 131  true_node.position         4789 non-null   float64
 132  true_node.abs_pos          4789 non-null   float64
 133  true_node.emoji            4789 non-null   object
 134  true_node.point_type       4789 non-null   object
 135  true_node.house            4789 non-null   object
 136  true_node.retrograde       4789 non-null   bool
 137  mean_node.name             4789 non-null   object
 138  mean_node.quality          4789 non-null   object
 139  mean_node.element          4789 non-null   object
 140  mean_node.sign             4789 non-null   object
 141  mean_node.sign_num         4789 non-null   int64
 142  mean_node.position         4789 non-null   float64
 143  mean_node.abs_pos          4789 non-null   float64
 144  mean_node.emoji            4789 non-null   object
 145  mean_node.point_type       4789 non-null   object
 146  mean_node.house            4789 non-null   object
 147  mean_node.retrograde       4789 non-null   bool
 148  chiron.name                4789 non-null   object
 149  chiron.quality             4789 non-null   object
 150  chiron.element             4789 non-null   object
 151  chiron.sign                4789 non-null   object
 152  chiron.sign_num            4789 non-null   int64
 153  chiron.position            4789 non-null   float64
 154  chiron.abs_pos             4789 non-null   float64
 155  chiron.emoji               4789 non-null   object
 156  chiron.point_type          4789 non-null   object
 157  chiron.house               4789 non-null   object
 158  chiron.retrograde          4789 non-null   bool
 159  mean_lilith.name           4789 non-null   object
 160  mean_lilith.quality        4789 non-null   object
 161  mean_lilith.element        4789 non-null   object
 162  mean_lilith.sign           4789 non-null   object
 163  mean_lilith.sign_num       4789 non-null   int64
 164  mean_lilith.position       4789 non-null   float64
 165  mean_lilith.abs_pos        4789 non-null   float64
 166  mean_lilith.emoji          4789 non-null   object
 167  mean_lilith.point_type     4789 non-null   object
 168  mean_lilith.house          4789 non-null   object
 169  mean_lilith.retrograde     4789 non-null   bool
 170  first_house.name           4789 non-null   object
 171  first_house.quality        4789 non-null   object
 172  first_house.element        4789 non-null   object
 173  first_house.sign           4789 non-null   object
 174  first_house.sign_num       4789 non-null   int64
 175  first_house.position       4789 non-null   float64
 176  first_house.abs_pos        4789 non-null   float64
 177  first_house.emoji          4789 non-null   object
 178  first_house.point_type     4789 non-null   object
 179  first_house.house          0 non-null      float64
 180  first_house.retrograde     0 non-null      float64
 181  second_house.name          4789 non-null   object
 182  second_house.quality       4789 non-null   object
 183  second_house.element       4789 non-null   object
 184  second_house.sign          4789 non-null   object
 185  second_house.sign_num      4789 non-null   int64
 186  second_house.position      4789 non-null   float64
 187  second_house.abs_pos       4789 non-null   float64
 188  second_house.emoji         4789 non-null   object
 189  second_house.point_type    4789 non-null   object
 190  second_house.house         0 non-null      float64
 191  second_house.retrograde    0 non-null      float64
 192  third_house.name           4789 non-null   object
 193  third_house.quality        4789 non-null   object
 194  third_house.element        4789 non-null   object
 195  third_house.sign           4789 non-null   object
 196  third_house.sign_num       4789 non-null   int64
 197  third_house.position       4789 non-null   float64
 198  third_house.abs_pos        4789 non-null   float64
 199  third_house.emoji          4789 non-null   object
 200  third_house.point_type     4789 non-null   object
 201  third_house.house          0 non-null      float64
 202  third_house.retrograde     0 non-null      float64
 203  fourth_house.name          4789 non-null   object
 204  fourth_house.quality       4789 non-null   object
 205  fourth_house.element       4789 non-null   object
 206  fourth_house.sign          4789 non-null   object
 207  fourth_house.sign_num      4789 non-null   int64
 208  fourth_house.position      4789 non-null   float64
 209  fourth_house.abs_pos       4789 non-null   float64
 210  fourth_house.emoji         4789 non-null   object
 211  fourth_house.point_type    4789 non-null   object
 212  fourth_house.house         0 non-null      float64
 213  fourth_house.retrograde    0 non-null      float64
 214  fifth_house.name           4789 non-null   object
 215  fifth_house.quality        4789 non-null   object
 216  fifth_house.element        4789 non-null   object
 217  fifth_house.sign           4789 non-null   object
 218  fifth_house.sign_num       4789 non-null   int64
 219  fifth_house.position       4789 non-null   float64
 220  fifth_house.abs_pos        4789 non-null   float64
 221  fifth_house.emoji          4789 non-null   object
 222  fifth_house.point_type     4789 non-null   object
 223  fifth_house.house          0 non-null      float64
 224  fifth_house.retrograde     0 non-null      float64
 225  sixth_house.name           4789 non-null   object
 226  sixth_house.quality        4789 non-null   object
 227  sixth_house.element        4789 non-null   object
 228  sixth_house.sign           4789 non-null   object
 229  sixth_house.sign_num       4789 non-null   int64
 230  sixth_house.position       4789 non-null   float64
 231  sixth_house.abs_pos        4789 non-null   float64
 232  sixth_house.emoji          4789 non-null   object
 233  sixth_house.point_type     4789 non-null   object
 234  sixth_house.house          0 non-null      float64
 235  sixth_house.retrograde     0 non-null      float64
 236  seventh_house.name         4789 non-null   object
 237  seventh_house.quality      4789 non-null   object
 238  seventh_house.element      4789 non-null   object
 239  seventh_house.sign         4789 non-null   object
 240  seventh_house.sign_num     4789 non-null   int64
 241  seventh_house.position     4789 non-null   float64
 242  seventh_house.abs_pos      4789 non-null   float64
 243  seventh_house.emoji        4789 non-null   object
 244  seventh_house.point_type   4789 non-null   object
 245  seventh_house.house        0 non-null      float64
 246  seventh_house.retrograde   0 non-null      float64
 247  eighth_house.name          4789 non-null   object
 248  eighth_house.quality       4789 non-null   object
 249  eighth_house.element       4789 non-null   object
 250  eighth_house.sign          4789 non-null   object
 251  eighth_house.sign_num      4789 non-null   int64
 252  eighth_house.position      4789 non-null   float64
 253  eighth_house.abs_pos       4789 non-null   float64
 254  eighth_house.emoji         4789 non-null   object
 255  eighth_house.point_type    4789 non-null   object
 256  eighth_house.house         0 non-null      float64
 257  eighth_house.retrograde    0 non-null      float64
 258  ninth_house.name           4789 non-null   object
 259  ninth_house.quality        4789 non-null   object
 260  ninth_house.element        4789 non-null   object
 261  ninth_house.sign           4789 non-null   object
 262  ninth_house.sign_num       4789 non-null   int64
 263  ninth_house.position       4789 non-null   float64
 264  ninth_house.abs_pos        4789 non-null   float64
 265  ninth_house.emoji          4789 non-null   object
 266  ninth_house.point_type     4789 non-null   object
 267  ninth_house.house          0 non-null      float64
 268  ninth_house.retrograde     0 non-null      float64
 269  tenth_house.name           4789 non-null   object
 270  tenth_house.quality        4789 non-null   object
 271  tenth_house.element        4789 non-null   object
 272  tenth_house.sign           4789 non-null   object
 273  tenth_house.sign_num       4789 non-null   int64
 274  tenth_house.position       4789 non-null   float64
 275  tenth_house.abs_pos        4789 non-null   float64
 276  tenth_house.emoji          4789 non-null   object
 277  tenth_house.point_type     4789 non-null   object
 278  tenth_house.house          0 non-null      float64
 279  tenth_house.retrograde     0 non-null      float64
 280  eleventh_house.name        4789 non-null   object
 281  eleventh_house.quality     4789 non-null   object
 282  eleventh_house.element     4789 non-null   object
 283  eleventh_house.sign        4789 non-null   object
 284  eleventh_house.sign_num    4789 non-null   int64
 285  eleventh_house.position    4789 non-null   float64
 286  eleventh_house.abs_pos     4789 non-null   float64
 287  eleventh_house.emoji       4789 non-null   object
 288  eleventh_house.point_type  4789 non-null   object
 289  eleventh_house.house       0 non-null      float64
 290  eleventh_house.retrograde  0 non-null      float64
 291  twelfth_house.name         4789 non-null   object
 292  twelfth_house.quality      4789 non-null   object
 293  twelfth_house.element      4789 non-null   object
 294  twelfth_house.sign         4789 non-null   object
 295  twelfth_house.sign_num     4789 non-null   int64
 296  twelfth_house.position     4789 non-null   float64
 297  twelfth_house.abs_pos      4789 non-null   float64
 298  twelfth_house.emoji        4789 non-null   object
 299  twelfth_house.point_type   4789 non-null   object
 300  twelfth_house.house        0 non-null      float64
 301  twelfth_house.retrograde   0 non-null      float64
dtypes: bool(16), float64(78), int64(29), object(179)
memory usage: 10.6+ MB

In [ ]:
astro_df

,full_name,number,team,position,birthdate,active,espn_id,sleeper_id,birthplace,latitude,...,twelfth_house.quality,twelfth_house.element,twelfth_house.sign,twelfth_house.sign_num,twelfth_house.position,twelfth_house.abs_pos,twelfth_house.emoji,twelfth_house.point_type,twelfth_house.house,twelfth_house.retrograde
1,GJ Kinne,2,PHI,QB,1988-12-01,False,15299,1,"Mesquite, TX",32.766610,...,Cardinal,Earth,Cap,9,22.587815,292.587815,♑️,House,NaN,NaN
3,David Harris,45,FA,LB,1984-01-21,False,10491,3,"Grand Rapids, MI",42.963242,...,Mutable,Water,Pis,11,14.572143,344.572143,♓️,House,NaN,NaN
4,Roddy White,84,FA,WR,1981-11-02,False,8442,4,"James Island, SC",32.734346,...,Mutable,Fire,Sag,8,26.461439,266.461439,♐️,House,NaN,NaN
5,Dallas Clark,87,FA,TE,1979-06-12,False,4482,5,"Livermore, IA",42.868324,...,Fixed,Fire,Leo,4,10.258602,130.258602,♌️,House,NaN,NaN
6,Brandon Mebane,92,FA,DT,1985-01-15,True,10529,6,"Los Angeles, CA",34.053691,...,Mutable,Water,Pis,11,25.891687,355.891687,♓️,House,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12357,David Martin-Robinson,88,TEN,TE,1999-12-26,True,4360978,12357,"Landisville, PA",40.095120,...,Fixed,Air,Aqu,10,23.014166,323.014166,♒️,House,NaN,NaN
12385,Jude McAtamney,99,NYG,PK,2000-05-09,True,5092436,12385,"Derry, Ireland",54.997868,...,Cardinal,Water,Can,3,17.634914,107.634914,♋️,House,NaN,NaN
12402,Ramon Jefferson,45,TBB,RB,2000-01-10,True,4250013,12402,"Bronx, NY",40.846651,...,Mutable,Water,Pis,11,16.491191,346.491191,♓️,House,NaN,NaN
12420,Gable Steveson,61,BUF,DT,2000-05-31,True,5214652,12420,"Apple Valley, MN",44.731909,...,Fixed,Fire,Leo,4,2.725535,122.725535,♌️,House,NaN,NaN
12421,David Wallis,30,NEP,WR,2001-08-08,True,5215032,12421,"Cedar Point, NC",34.687630,...,Cardinal,Air,Lib,6,0.137548,180.137548,♎️,House,NaN,NaN

In [ ]:
astro_df.to_parquet(path='/content/drive/MyDrive/ff/astro.parquet', compression='snappy')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[4775 rows x 0 columns]

[1,
 10,
 100,
 1000,
 1001,
 1002,
 1003,
 1004,
 1005,
 1006,
 1007,
 1008,
 1009,
 101,
 1010,
 1013,
 1014,
 1015,
 1017,
 1018,
 1019,
 102,
 1020,
 10222,
 10225,
 10229,
 10236,
 1024,
 1025,
 1026,
 1027,
 1028,
 1029,
 103,
 1030,
 1032,
 1033,
 1034,
 1035,
 1036,
 1037,
 1038,
 1039,
 104,
 1040,
 1041,
 1042,
 1043,
 1045,
 1046,
 1047,
 1048,
 1049,
 105,
 1050,
 1051,
 1052,
 1053,
 1054,
 1056,
 1057,
 1059,
 106,
 1060,
 1061,
 1062,
 1063,
 1064,
 1065,
 1066,
 1067,
 1068,
 1069,
 107,
 1071,
 1072,
 1073,
 1075,
 1076,
 1077,
 1078,
 1079,
 108,
 1080,
 1081,
 1082,
 1084,
 1085,
 10859,
 1086,
 10860,
 10869,
 1089,
 109,
 1090,
 10905,
 1091,
 10919,
 1092,
 10929,
 1093,
 10937,
 1094,
 10945,
 1095,
 10958,
 1096,
 1097,
 10971,
 10975,
 1099,
 10997,
 11,
 110,
 1100,
 11006,
 11018,
 1102,
 1103,
 11032,
 1104,
 11046,
 1105,
 1106,
 1107,
 11076,
 11077,
 1108,
 1109,
 111,
 1110,
 1111,
 1112,
 1113,
 11133,
 1114,
 1115,
 1116,
 1117,
 1118,
 112,
 1120,
 1121,
 1122,
 1123,
 11232,
 11237,
 1124,
 1125,
 1126,
 1127,
 11270,
 1128,
 11297,
 1130,
 1131,
 1133,
 1135,
 1136,
 1137,
 1138,
 1139,
 114,
 1141,
 1143,
 1144,
 1145,
 1146,
 1147,
 11470,
 11474,
 1148,
 1149,
 11495,
 115,
 1150,
 1151,
 1152,
 11533,
 11539,
 1154,
 1155,
 11556,
 11557,
 11559,
 1156,
 11560,
 11563,
 11564,
 11565,
 11566,
 11567,
 11568,
 1157,
 11570,
 11571,
 11575,
 11576,
 11577,
 11579,
 1158,
 11580,
 11581,
 11583,
 11586,
 11589,
 11590,
 11592,
 11595,
 11596,
 11597,
 1160,
 11603,
 11604,
 1161,
 11610,
 11615,
 11617,
 11618,
 11619,
 1162,
 11620,
 11623,
 11624,
 11625,
 11627,
 11628,
 11629,
 1163,
 11631,
 11635,
 11637,
 11638,
 1164,
 11640,
 11643,
 11645,
 11646,
 11647,
 11648,
 1165,
 11658,
 1166,
 11661,
 11662,
 11663,
 11665,
 11667,
 1167,
 11674,
 11675,
 11676,
 11677,
 11678,
 11679,
 11682,
 11686,
 11687,
 11688,
 11689,
 1169,
 11691,
 11692,
 11693,
 11694,
 11695,
 11698,
 11699,
 117,
 1170,
 11700,
 11701,
 11703,
 11705,
 11706,
 1171,
 11710,
 11712,
 11714,
 11717,
 11721,
 11722,
 11725,
 11726,
 11727,
 11728,
 1173,
 11730,
 11732,
 11734,
 11736,
 11739,
 1174,
 11740,
 11741,
 11742,
 11743,
 11744,
 11748,
 1175,
 11751,
 11752,
 11753,
 11754,
 11755,
 11757,
 11759,
 1176,
 11760,
 11762,
 11763,
 1177,
 11770,
 11771,
 11781,
 11783,
 11785,
 11787,
 11789,
 1179,
 11797,
 11798,
 11799,
 118,
 1180,
 11801,
 11806,
 11807,
 1181,
 1182,
 11820,
 11821,
 11822,
 1185,
 1186,
 11864,
 11886,
 1189,
 11895,
 119,
 1190,
 11901,
 11906,
 11907,
 1191,
 1192,
 11925,
 1193,
 1194,
 11941,
 11946,
 11947,
 1195,
 11951,
 1196,
 11969,
 1197,
 1198,
 11989,
 1199,
 11990,
 120,
 1200,
 12005,
 1201,
 12015,
 1202,
 12029,
 1203,
 12031,
 1204,
 12045,
 1205,
 12057,
 1206,
 12068,
 1207,
 12070,
 1208,
 12080,
 1209,
 121,
 1210,
 1211,
 12111,
 1213,
 12130,
 12133,
 12139,
 1214,
 1215,
 1216,
 12172,
 1218,
 1219,
 122,
 1221,
 12210,
 12212,
 12224,
 1223,
 1224,
 12242,
 1225,
 1226,
 1228,
 1229,
 1230,
 1231,
 1232,
 1233,
 1234,
 1235,
 12357,
 1236,
 1237,
 1238,
 12385,
 1240,
 12402,
 1241,
 1242,
 12420,
 12421,
 1243,
 1244,
 1245,
 1246,
 1247,
 1249,
 125,
 1250,
 1251,
 1252,
 1253,
 1254,
 1255,
 1256,
 1258,
 1259,
 126,
 1260,
 1262,
 1263,
 1264,
 1265,
 1266,
 127,
 1270,
 1271,
 1272,
 1274,
 1275,
 1276,
 1277,
 1278,
 1279,
 128,
 1281,
 1282,
 1283,
 1284,
 1285,
 1286,
 1287,
 1288,
 1289,
 129,
 1290,
 1291,
 1292,
 1293,
 1294,
 1296,
 1297,
 1298,
 1299,
 13,
 130,
 1300,
 1301,
 1302,
 1303,
 1304,
 1305,
 1306,
 1307,
 1308,
 1311,
 1312,
 1313,
 1314,
 1317,
 1319,
 132,
 1320,
 1321,
 1322,
 1323,
 1324,
 1325,
 1326,
 1328,
 1329,
 133,
 133,
 1330,
 1331,
 1332,
 1333,
 1334,
 1336,
 1337,
 1338,
 1339,
 134,
 1341,
 1342,
 1343,
 1344,
 1345,
 1346,
 1347,
 1348,
 1349,
 135,
 1350,
 1351,
 1352,
 1353,
 1354,
 1355,
 1356,
 1357,
 1359,
 1361,
 1362,
 1363,
 1364,
 1365,
 1366,
 1367,
 1369,
 137,
 1371,
 1372,
 1373,
 1375,
 1376,
 1377,
 1379,
 138,
 1380,
 1381,
 1383,
 1384,
 1386,
 1387,
 1388,
 139,
 1390,
 1392,
 1393,
 1394,
 1395,
 1396,
 1399,
 14,
 140,
 1400,
 1402,
 1404,
 1405,
 1408,
 1409,
 141,
 1410,
 1411,
 1412,
 1413,
 1414,
 1415,
 1416,
 1417,
 1418,
 142,
 1420,
 1422,
 1423,
 1425,
 1426,
 1429,
 1430,
 1433,
 1434,
 1436,
 1438,
 144,
 1440,
 1441,
 1442,
 1443,
 1444,
 1445,
 1446,
 1448,
 1449,
 145,
 1450,
 1451,
 1453,
 1454,
 1455,
 1456,
 1458,
 1459,
 146,
 1460,
 1461,
 1462,
 1463,
 1465,
 1466,
 1468,
 147,
 1471,
 1472,
 1473,
 1474,
 1475,
 1476,
 1477,
 1479,
 148,
 1482,
 1483,
 1484,
 1485,
 1487,
 1488,
 1489,
 149,
 1490,
 1491,
 1492,
 1494,
 1495,
 1497,
 1498,
 1499,
 15,
 150,
 1500,
 1501,
 1502,
 1503,
 1504,
 1505,
 1506,
 1507,
 151,
 1511,
 1512,
 1513,
 1514,
 1515,
 1516,
 1517,
 1518,
 152,
 1522,
 1523,
 1524,
 1525,
 1526,
 1527,
 1528,
 153,
 1530,
 1532,
 1533,
 1534,
 1535,
 1536,
 1537,
 1539,
 154,
 1540,
 1541,
 1542,
 1543,
 1544,
 1545,
 1546,
 1547,
 1548,
 1549,
 155,
 1550,
 1551,
 1553,
 1554,
 1555,
 1556,
 1557,
 1558,
 1559,
 156,
 1560,
 1561,
 1562,
 1563,
 1564,
 1565,
 1567,
 157,
 1570,
 1571,
 1572,
 1573,
 1575,
 1576,
 1577,
 1578,
 1579,
 158,
 1582,
 1583,
 1584,
 1585,
 1586,
 1587,
 1588,
 1589,
 159,
 1590,
 1592,
 1593,
 1595,
 1596,
 1597,
 1599,
 16,
 160,
 1600,
 1601,
 1602,
 1603,
 1604,
 1606,
 1608,
 1609,
 161,
 1610,
 1612,
 1614,
 1616,
 1617,
 1618,
 1619,
 1620,
 1623,
 1625,
 1626,
 1627,
 1628,
 1630,
 1631,
 1633,
 1636,
 1638,
 164,
 1640,
 1641,
 1642,
 1643,
 1644,
 1646,
 1648,
 1649,
 165,
 1654,
 1655,
 1656,
 1657,
 166,
 1660,
 1661,
 1662,
 1663,
 1665,
 1666,
 1667,
 167,
 1670,
 1671,
 1672,
 1673,
 1674,
 1675,
 1676,
 1679,
 168,
 1680,
 1681,
 1682,
 1683,
 1684,
 1685,
 1686,
 1688,
 1689,
 169,
 1692,
 1693,
 1694,
 1695,
 1696,
 1697,
 1698,
 1699,
 17,
 170,
 1700,
 1701,
 1703,
 1704,
 1706,
 1707,
 1708,
 1709,
 171,
 1710,
 1713,
 1715,
 1716,
 1717,
 1718,
 172,
 1720,
 1724,
 1729,
 1732,
 1733,
 1734,
 1735,
 1736,
 1737,
 1739,
 1740,
 1741,
 1742,
 1743,
 1747,
 1749,
 175,
 1750,
 1755,
 1756,
 1758,
 1759,
 176,
 1761,
 1762,
 1764,
 1765,
 177,
 1770,
 1772,
 1774,
 1775,
 1777,
 1778,
 178,
 1780,
 1785,
 1786,
 1787,
 1788,
 179,
 1790,
 1792,
 1793,
 1794,
 1796,
 1798,
 180,
 1800,
 1802,
 1803,
 1806,
 1807,
 1808,
 1809,
 181,
 1813,
 1815,
 1817,
 1818,
 1819,
 182,
 1820,
 1821,
 1823,
 1825,
 1827,
 1828,
 183,
 1830,
 1831,
 1833,
 1834,
 1835,
 1837,
 1838,
 184,
 1841,
 1843,
 1845,
 1847,
 1848,
 1849,
 185,
 1851,
 1853,
 1854,
 1855,
 1856,
 1857,
 1858,
 186,
 1861,
 1862,
 1864,
 1865,
 1866,
 1868,
 187,
 1871,
 1872,
 1874,
 1875,
 1876,
 1877,
 1879,
 188,
 1880,
 1881,
 1883,
 1885,
 1886,
 1887,
 1889,
 189,
 1891,
 1892,
 1895,
 1897,
 1898,
 1899,
 1899,
 19,
 1901,
 1902,
 1903,
 1904,
 1905,
 1906,
 1907,
 1908,
 1909,
 191,
 1910,
 1911,
 1912,
 1913,
 1914,
 1916,
 1919,
 192,
 1920,
 1921,
 1924,
 1925,
 1928,
 1929,
 193,
 1932,
 1935,
 1937,
 194,
 1940,
 1941,
 1942,
 1944,
 1945,
 1946,
 1947,
 1948,
 195,
 ...]

In [ ]:
#

NameError: name 'astro_pop_df' is not defined